'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
export type CatalogueService = { id: string; code: string; name: Record<string, string>; note: Record<string, string> | null; sectionId: string; section: { title: Record<string, string> }; price: string; amount: string; unit: string; mode: string; currency: string };
export type ServiceSelection = { cataloguePriceItemId: string; serviceName: string; serviceNameDe: string; description: string; descriptionDe: string; quantity: string; unit: string; unitPrice: string; priceMode: string; priceConfirmed: boolean; taxTreatment: string };
const text = (values: Record<string, string> | null | undefined) => Object.values(values ?? {}).join(' ');
export function ServicePicker({ onSelect, onClose }: { onSelect: (line: ServiceSelection) => void; onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null); const search = useRef<HTMLInputElement>(null);
  const [items, setItems] = useState<CatalogueService[]>([]), [query, setQuery] = useState(''), [loading, setLoading] = useState(true), [error, setError] = useState(''), [attempt, setAttempt] = useState(0), [active, setActive] = useState(0);
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; dialog.current?.showModal(); search.current?.focus(); const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = overflow; previous?.focus(); }; }, []);
  useEffect(() => { const controller = new AbortController(); async function load() { setLoading(true); setError(''); try { const all: CatalogueService[] = []; let cursor: string | null = null; do { const response: Response = await fetch('/api/admin/catalogue' + (cursor ? '?cursor=' + encodeURIComponent(cursor) : ''), { signal: controller.signal }); if (!response.ok) throw new Error('Could not load services. Retry to keep your current edits.'); const data: { items: CatalogueService[]; nextCursor: string | null } = await response.json(); all.push(...data.items); cursor = data.nextCursor; } while (cursor); if (!controller.signal.aborted) setItems(all); } catch (e) { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : 'Request failed.'); } finally { if (!controller.signal.aborted) setLoading(false); } } void load(); return () => controller.abort(); }, [attempt]);
  const results = useMemo(() => { const term = query.trim().toLocaleLowerCase(); return items.filter(item => { const haystack = `${item.code} ${text(item.name)} ${text(item.note)} ${text(item.section.title)}`.toLocaleLowerCase(); const aliases = /clean|reinig/.test(haystack) ? ' cleaning reinigung ' : ''; return (haystack + aliases).includes(term); }); }, [items, query]);
  function choose(item?: CatalogueService) { onSelect({ cataloguePriceItemId: item?.id ?? '', serviceName: item?.name.en ?? '', serviceNameDe: item?.name.de ?? '', description: item?.note?.en ?? '', descriptionDe: item?.note?.de ?? '', quantity: '1', unit: item?.unit ?? 'item', unitPrice: item?.amount ?? '', priceMode: item?.mode ?? 'MANUAL', priceConfirmed: !!item && ['FIXED', 'HOURLY'].includes(item.mode), taxTreatment: 'UNCONFIRMED' }); onClose(); }
  return <dialog ref={dialog} className="service-picker" aria-labelledby="service-picker-title" onCancel={event => { event.preventDefault(); onClose(); }}>
    <div className="service-picker__heading"><h2 id="service-picker-title">Add service</h2><button type="button" aria-label="Close service picker" onClick={onClose}>Close</button></div>
    <label>Search services<input ref={search} value={query} placeholder="cleaning, Reinigung, service or code" role="combobox" aria-autocomplete="list" aria-expanded="true" aria-controls="service-results" aria-activedescendant={results[active] ? `service-${results[active].id}` : undefined} onChange={event => { setQuery(event.target.value); setActive(0); }} onKeyDown={event => { if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); const next = Math.max(0, Math.min(results.length - 1, active + (event.key === 'ArrowDown' ? 1 : -1))); setActive(next); document.getElementById(`service-${results[next]?.id}`)?.scrollIntoView({ block: 'nearest' }); } if (event.key === 'Enter' && !loading && results[active]) { event.preventDefault(); choose(results[active]); } }} /></label>
    <p role="status">{loading ? 'Loading catalogue…' : error || (results.length ? `${results.length} services` : 'No matching services. Try another search or add a custom service.')}</p>
    {error ? <button type="button" onClick={() => setAttempt(value => value + 1)}>Retry</button> : null}
    <div id="service-results" role="listbox" aria-label="Catalogue services" className="service-picker__results">{!loading && !error && results.map((item, index) => <button type="button" role="option" aria-selected={index === active} id={`service-${item.id}`} key={item.id} onClick={() => choose(item)}><strong>{item.name.en || '[English name missing]'} · {item.name.de || '[German name missing]'}</strong><span>{item.section.title.en || item.section.title.de} · {item.code}</span><span>{item.amount || 'Agree price'} {item.currency} · {item.mode.toLowerCase()} · {item.unit}</span></button>)}</div>
    <button type="button" className="admin-primary" onClick={() => choose()}>Create custom service for this document</button><p>Custom lines stay private. To publish one, use the separate <a href="/dashboard/prices" target="_blank" rel="noreferrer">catalogue editor</a> and save it explicitly.</p>
  </dialog>;
}
