import type { Locale } from '@tiladys/shared';
import { translatedServiceContent } from './service-translations';

export const serviceIds = [
  'pc-laptop', 'websites', 'business-it',
] as const;

export type ServiceId = (typeof serviceIds)[number];
export const legacyServiceRedirects = {
  'it-support-diagnostics': 'pc-laptop',
  'data-backup': 'pc-laptop',
  'pc-cleaning-upgrades': 'pc-laptop',
  security: 'pc-laptop',
  'network-wifi': 'business-it',
  'google-business': 'business-it',
  'business-photography': 'business-it',
  'digital-design': 'business-it',
  'training-consulting': 'business-it',
} as const;
export type LegacyServiceId = keyof typeof legacyServiceRedirects;
export type ServicePriceRef = { code: string; label: Record<Locale, string> };
export type ServiceDefinition = {
  id: ServiceId;
  priceRefs: ServicePriceRef[];
  related: ServiceId[];
  image: string;
};

const label = (en: string, de: string, uk: string, ru: string, sk: string, fr: string): Record<Locale, string> => ({ en, de, uk, ru, sk, fr });

export const serviceDefinitions: ServiceDefinition[] = [
  { id: 'pc-laptop', image: '/services/tiladys-service-pc-laptop.webp?v=20260920', priceRefs: [
    { code: 'B10', label: label('Software installation', 'Softwareinstallation', 'Встановлення програм', 'Установка программ', 'Inštalácia softvéru', 'Installation de logiciel') },
    { code: 'A02', label: label('Basic diagnostics', 'Basisdiagnose', 'Базова діагностика', 'Базовая диагностика', 'Základná diagnostika', 'Diagnostic de base') },
    { code: 'E01', label: label('Desktop cleaning', 'Desktop-PC-Reinigung', 'Чищення настільного ПК', 'Чистка настольного ПК', 'Čistenie stolného PC', 'Nettoyage PC fixe') },
    { code: 'E05', label: label('Desktop upgrade', 'Desktop-PC-Upgrade', 'Модернізація настільного ПК', 'Модернизация настольного ПК', 'Vylepšenie stolného PC', 'Mise à niveau PC fixe') },
    { code: 'E11', label: label('Office PC assembly', 'Office-PC-Zusammenbau', 'Складання офісного ПК', 'Сборка офисного ПК', 'Zostavenie kancelárskeho PC', 'Assemblage PC bureautique') },
    { code: 'D04', label: label('Local backup setup', 'Lokale Backup-Einrichtung', 'Налаштування локальної копії', 'Настройка локальной копии', 'Nastavenie lokálnej zálohy', 'Configuration de sauvegarde locale') },
  ], related: ['websites', 'business-it'] },
  { id: 'websites', image: '/services/tiladys-service-website-creation.png', priceRefs: [
    { code: 'H02', label: label('Subscription website', 'Website im Abonnement', 'Сайт за підпискою', 'Сайт по подписке', 'Web na predplatné', 'Site web par abonnement') },
    { code: 'H06', label: label('One-page website ownership', 'Onepage-Website zum Kauf', 'Односторінковий сайт у власність', 'Одностраничный сайт в собственность', 'Jednostránkový web do vlastníctva', 'Site one-page en pleine propriété') },
    { code: 'H10', label: label('Landing page', 'Landingpage', 'Лендінг', 'Лендинг', 'Landing page', 'Page d’atterrissage') },
  ], related: ['pc-laptop', 'business-it'] },
  { id: 'business-it', image: '/services/tiladys-service-business-it-digital.webp?v=20260920', priceRefs: [
    { code: 'G01', label: label('Business IT setup', 'Business-IT-Einrichtung', 'Налаштування IT для бізнесу', 'Настройка IT для бизнеса', 'Nastavenie firemného IT', 'Configuration IT professionnelle') },
    { code: 'F01', label: label('Network setup', 'Netzwerk-Einrichtung', 'Налаштування мережі', 'Настройка сети', 'Nastavenie siete', 'Configuration réseau') },
    { code: 'I01', label: label('Google Business', 'Google Business', 'Google Business', 'Google Business', 'Google Business', 'Google Business') },
    { code: 'J01', label: label('Business photography', 'Business-Fotografie', 'Фотографія для бізнесу', 'Фотография для бизнеса', 'Firemná fotografia', 'Photographie professionnelle') },
    { code: 'K02', label: label('Digital design', 'Digitales Design', 'Цифровий дизайн', 'Цифровой дизайн', 'Digitálny dizajn', 'Design numérique') },
  ], related: ['websites', 'pc-laptop'] },
];

export const serviceById = Object.fromEntries(serviceDefinitions.map((service) => [service.id, service])) as Record<ServiceId, ServiceDefinition>;

export function isServiceId(value: string): value is ServiceId {
  return serviceIds.includes(value as ServiceId);
}

export function isLegacyServiceId(value: string): value is LegacyServiceId {
  return Object.prototype.hasOwnProperty.call(legacyServiceRedirects, value);
}

export function contactServiceId(value: string): ServiceId | null {
  if (isServiceId(value)) return value;
  if (isLegacyServiceId(value)) return legacyServiceRedirects[value];
  return null;
}

export type ServiceCopy = {
  title: string; short: string; intro: string[]; examples: string[];
  groups?: Array<{ title: string; items: string[] }>;
  expected: string; limitations?: string; metaTitle: string; metaDescription: string;
};

type CompactCopy = [string, string, string, string[], string, string?];
const c = (title: string, short: string, intro: string, examples: string[], expected: string, limitations?: string): CompactCopy => [title, short, intro, examples, expected, limitations];

const localized: Record<Locale, Record<string, CompactCopy>> = {
  en: {
    'it-support-diagnostics': c('IT Support & Diagnostics', 'Clear troubleshooting for computers, software and everyday technical problems.', 'When the cause is unclear, a structured diagnosis is the right first step. TiLADYS checks the symptoms, explains the options in plain language and recommends practical next steps for private customers and small businesses.', ['Basic PC and laptop diagnostics', 'Extended diagnostics with a written report', 'Remote IT support', 'Workshop service', 'On-site support in the local area', 'Software and startup troubleshooting', 'Same-day handling when available'], 'You receive a clear assessment, understandable recommendations and an estimate before additional work begins.', 'A diagnosis cannot guarantee repair when hardware is physically damaged or a third-party service is unavailable.'),
    'pc-laptop': c('PC & Laptop Services', 'Practical help with setup, software, performance problems and everyday computer tasks.', 'From a new-device setup to a computer that no longer starts correctly, TiLADYS helps make your system usable and understandable. Support is available for Windows, Linux, common applications and connected office devices.', ['New computer setup', 'Windows installation and setup', 'Linux installation and setup', 'Software installation', 'Microsoft Office setup', 'Email account setup', 'Printer and scanner setup', 'Windows and driver updates', 'Performance optimization', 'Boot and software troubleshooting'], 'Your computer is configured for its intended use, tested and handed back with a clear explanation of what was changed.', 'Board-level electronics repair, soldering and illegal software activation are not offered.'),
    security: c('Security & Account Protection', 'Practical protection for devices, browsers, passwords and online accounts.', 'TiLADYS helps reduce common security risks without unnecessary complexity. The service is suitable for private users and small workplaces that need safer settings, cleaner devices and better account protection.', ['Virus and unwanted-software scan', 'Malware removal', 'Device security configuration', 'Two-factor authentication setup', 'Password-manager setup', 'Browser and extension review', 'Account recovery assistance', 'Parental controls', 'Workstation security check', 'Phishing-awareness guidance'], 'You receive a cleaner, better-configured system and practical guidance for safer daily use.', 'No hacking, password cracking, forensic investigation, penetration testing or guaranteed recovery of compromised accounts is offered.'),
    'data-backup': c('Data & Backup', 'Move, organize and protect important files with a practical backup plan.', 'TiLADYS helps transfer data to a new device, set up local or cloud backups and organize important files. The approach is matched to the amount of data, available devices and the level of protection you need.', ['Data transfer between devices', 'SSD or HDD cloning', 'Local backup setup', 'Cloud backup setup', '3-2-1 backup planning', 'Logical deleted-file recovery', 'Secure software-based wiping', 'File and folder organization', 'Photo archive organization'], 'Your files are transferred or backed up in a clear structure, with the setup tested and explained.', 'Physical clean-room recovery is not offered. Logical recovery success depends on the condition of the storage device and whether data has been overwritten.'),
    'pc-cleaning-upgrades': c('PC Cleaning & Upgrades', 'Cleaning, modular component upgrades and custom PC assembly.', 'Dust, heat and outdated components can make a computer noisy or slow. TiLADYS provides careful internal cleaning, modular upgrades and assembly using compatible, replaceable components.', ['Desktop internal cleaning', 'Laptop internal cleaning', 'Thermal paste replacement', 'RAM installation', 'SSD or HDD installation', 'Graphics-card installation', 'Power-supply module replacement', 'Cooling component replacement', 'Custom PC assembly', 'Stability and temperature testing'], 'The device is cleaned or upgraded, checked for stable operation and returned with a summary of the completed work.', 'Component costs are separate unless stated. Board-level repair, soldering and power-supply electronics repair are not offered.'),
    'network-wifi': c('Network & Wi-Fi', 'Reliable setup and troubleshooting for routers, Wi-Fi, network devices and NAS.', 'TiLADYS configures existing home and small-business network equipment and helps improve everyday connectivity. Work focuses on devices, settings, coverage and clear documentation.', ['Router and FRITZ!Box setup', 'Wi-Fi and Mesh setup', 'Access-point configuration', 'Managed-switch configuration', 'Guest Wi-Fi and parental rules', 'Network printer setup', 'Basic NAS setup', 'VLAN and advanced configuration', 'Network documentation', 'Firmware updates'], 'You receive a tested network configuration, clearer access rules and practical recommendations for any remaining coverage or hardware needs.', 'Permanent cabling, drilling, mounting, cable certification, electrical work and work on mains voltage are not offered.'),
    'business-it': c('Business IT', 'Straightforward workplace, email and cloud support for self-employed professionals and small businesses.', 'TiLADYS sets up the everyday digital tools a small business needs without enterprise complexity. Services cover professional email, shared cloud files, meetings, workstations and clear IT documentation.', ['Professional domain email', 'Microsoft 365 setup', 'Google Workspace setup', 'Email migration', 'OneDrive, Google Drive or Dropbox', 'Shared folders and permissions', 'Teams, Zoom or Google Meet', 'New-workstation setup', 'IT inventory and documentation', 'Recurring IT support plans'], 'Your team receives a practical, organized setup with access rights and essential steps documented.', 'Licences and third-party subscriptions are separate. Provider availability and migration timing cannot be guaranteed.'),
    websites: c('Website Services', 'Professional websites, landing pages, hosting and ongoing support for small businesses.', 'TiLADYS plans and builds practical websites that work on phones, tablets and desktops. Choose a website subscription with ongoing service or purchase a website for full ownership; these are separate offers with different pricing and responsibilities. Existing sites can also be redesigned, optimized or maintained.', ['Website consultation and planning', 'Subscription or rental websites', 'One-page and small-business websites', 'Custom websites and landing pages', 'Basic online shops', 'Redesign and mobile optimization', 'Forms and booking integrations', 'Multilingual websites and basic SEO', 'Domain, hosting and SSL setup', 'Maintenance, updates and content uploads'], 'You receive a tested website solution matched to the agreed scope, with ownership, hosting and ongoing responsibilities explained before work starts.', 'Search position, visitor numbers and results from third-party integrations cannot be guaranteed. Accessibility improvements are not a certified audit.'),
    'google-business': c('Google Business & Local Visibility', 'Set up and improve your business profile so customers find accurate, useful information.', 'TiLADYS helps small local businesses create, review and maintain a clear Google Business presence. The focus is accurate information, useful content and consistent local visibility basics.', ['Profile creation and setup', 'Existing profile audit', 'Business categories and description', 'Contact and service information', 'Business photos', 'Google posts', 'Review-response templates', 'Review QR code', 'Local visibility review', 'Directory consistency'], 'Your profile is more complete, consistent and easier for customers to understand.', 'Google controls verification, rankings, Maps placement and review decisions. These outcomes and customer traffic cannot be guaranteed.'),
    'business-photography': c('Business Photography', 'Clean, practical photography for websites, profiles, products and business communication.', 'TiLADYS creates focused visual content for small businesses and digital profiles. Sessions are scoped for practical website, Google Business and social-media use.', ['Mini business photography session', 'Regular business photography session', 'Website photography', 'Google Business photography', 'Simple product photography', 'Editing customer-supplied photos', 'Resizing for websites', 'Exports for social media'], 'You receive edited images in formats suited to the agreed digital channels and usage.', 'Complex studio productions, specialist product shoots and services outside the agreed TiLADYS photography scope require another provider.'),
    'digital-design': c('Digital Design & Business Materials', 'Useful branded materials for daily business communication online and in print.', 'TiLADYS turns essential business information into clear, consistent digital materials. The focus is practical assets that customers and small teams can use immediately.', ['Business social-profile setup', 'Professional email signatures', 'Digital business cards', 'QR codes', 'Printed business-card design', 'Service-sheet and price-list design', 'Basic brand kits', 'Digital catalogs and menus', 'Online forms', 'Simple no-code automation'], 'You receive ready-to-use files or configured digital tools in the formats agreed for your channels.', 'Printing, complex brand strategy and custom software development are separate from these basic design services.'),
    'training-consulting': c('Training & Consulting', 'Friendly guidance for computer use, purchases and small-business digital decisions.', 'You do not need technical knowledge to ask for help. TiLADYS offers individual or small-team training, practical purchase advice and clear written instructions tailored to your situation.', ['Individual computer training', 'Small-team computer training', 'PC and laptop purchase advice', 'Small-business digitalization consultation', 'Written step-by-step instructions', 'Device pickup and delivery in Mülheim', 'Equipment purchasing assistance'], 'You leave with clearer next steps, practical knowledge or an informed purchasing plan suited to your needs and budget.', 'Advice is technical and practical, not legal, tax or certified data-protection consulting. Travel and purchased equipment may cost extra.'),
  },
  de: {
    'it-support-diagnostics': c('IT-Support & Diagnose', 'Strukturierte Fehlersuche bei Computern, Software und alltäglichen Technikproblemen.', 'Wenn die Ursache unklar ist, schafft eine strukturierte Diagnose Klarheit. TiLADYS prüft die Symptome, erklärt die Möglichkeiten verständlich und empfiehlt sinnvolle nächste Schritte für Privatkunden und kleine Unternehmen.', ['Basisdiagnose für PC und Laptop', 'Erweiterte Diagnose mit Bericht', 'IT-Fernsupport', 'Werkstattservice', 'Vor-Ort-Unterstützung in der Region', 'Fehler bei Software und Systemstart', 'Expressbearbeitung nach Verfügbarkeit'], 'Sie erhalten eine klare Einschätzung, verständliche Empfehlungen und vor weiteren Arbeiten eine Kostenschätzung.', 'Bei physisch beschädigter Hardware oder nicht verfügbaren Drittanbieterdiensten kann eine Diagnose keine Reparatur garantieren.'),
    'pc-laptop': c('PC- & Laptop-Service', 'Praktische Hilfe bei Einrichtung, Software, Leistungsproblemen und täglichen Computeraufgaben.', 'Ob neuer Computer oder ein System, das nicht mehr richtig startet: TiLADYS richtet Geräte verständlich und passend zum Einsatz ein. Unterstützung gibt es für Windows, Linux, gängige Programme und angeschlossene Bürogeräte.', ['Neuen Computer einrichten', 'Windows installieren und einrichten', 'Linux installieren und einrichten', 'Programme installieren', 'Microsoft Office einrichten', 'E-Mail-Konto einrichten', 'Drucker und Scanner einrichten', 'Windows und Treiber aktualisieren', 'Leistung optimieren', 'Start- und Softwarefehler beheben'], 'Ihr Computer wird für den vereinbarten Zweck eingerichtet, getestet und mit einer verständlichen Erklärung übergeben.', 'Reparaturen auf Platinenebene, Lötarbeiten und illegale Softwareaktivierungen werden nicht angeboten.'),
    security: c('Sicherheit & Kontoschutz', 'Praktischer Schutz für Geräte, Browser, Passwörter und Onlinekonten.', 'TiLADYS hilft, typische Sicherheitsrisiken ohne unnötige Komplexität zu reduzieren. Das Angebot eignet sich für Privatpersonen und kleine Arbeitsplätze, die sichere Einstellungen und besseren Kontoschutz benötigen.', ['Viren- und Schadsoftwareprüfung', 'Entfernung von Malware', 'Sichere Geräteeinstellungen', 'Zwei-Faktor-Authentifizierung', 'Passwortmanager einrichten', 'Browser und Erweiterungen prüfen', 'Hilfe bei Kontowiederherstellung', 'Kinderschutz einrichten', 'Sicherheitscheck am Arbeitsplatz', 'Hilfe zum Erkennen von Phishing'], 'Sie erhalten ein bereinigtes, besser abgesichertes System und praktische Hinweise für den sicheren Alltag.', 'Hacking, Passwortknacken, forensische Untersuchungen, Penetrationstests und garantierte Kontowiederherstellung werden nicht angeboten.'),
    'data-backup': c('Daten & Backup', 'Wichtige Dateien übertragen, ordnen und mit einem praktischen Backup schützen.', 'TiLADYS überträgt Daten auf neue Geräte, richtet lokale oder Cloud-Backups ein und hilft bei einer übersichtlichen Ablage. Die Lösung richtet sich nach Datenmenge, vorhandenen Geräten und gewünschter Sicherheit.', ['Daten zwischen Geräten übertragen', 'SSD oder HDD klonen', 'Lokales Backup einrichten', 'Cloud-Backup einrichten', '3-2-1-Backup planen', 'Logisch gelöschte Dateien wiederherstellen', 'Datenträger softwarebasiert löschen', 'Dateien und Ordner organisieren', 'Fotoarchive ordnen'], 'Ihre Dateien werden übersichtlich übertragen oder gesichert; die Einrichtung wird getestet und erklärt.', 'Physische Datenrettung im Reinraum wird nicht angeboten. Der Erfolg logischer Wiederherstellung hängt vom Zustand des Datenträgers ab.'),
    'pc-cleaning-upgrades': c('PC-Reinigung & Upgrades', 'Reinigung, modulare Aufrüstung und Zusammenbau von Computern.', 'Staub, Wärme und veraltete Komponenten können Computer laut oder langsam machen. TiLADYS übernimmt sorgfältige Innenreinigung, kompatible Aufrüstung und PC-Zusammenbau.', ['Desktop-PC innen reinigen', 'Laptop innen reinigen', 'Wärmeleitpaste erneuern', 'RAM einbauen', 'SSD oder HDD einbauen', 'Grafikkarte einbauen', 'Netzteilmodul austauschen', 'Kühlung austauschen', 'Individuellen PC zusammenbauen', 'Stabilität und Temperaturen testen'], 'Das Gerät wird gereinigt oder aufgerüstet, auf stabilen Betrieb geprüft und mit einer Zusammenfassung übergeben.', 'Komponenten kosten extra, sofern nicht anders vereinbart. Lötarbeiten und Reparaturen an Platinen oder Netzteilelektronik werden nicht angeboten.'),
    'network-wifi': c('Netzwerk & WLAN', 'Zuverlässige Einrichtung und Fehlersuche für Router, WLAN, Netzwerkgeräte und NAS.', 'TiLADYS konfiguriert vorhandene Netzwerkgeräte für Zuhause und kleine Unternehmen. Im Mittelpunkt stehen Geräteeinstellungen, Abdeckung, Zugriffsregeln und verständliche Dokumentation.', ['Router und FRITZ!Box einrichten', 'WLAN und Mesh einrichten', 'Access Point konfigurieren', 'Managed Switch konfigurieren', 'Gast-WLAN und Jugendschutzregeln', 'Netzwerkdrucker einrichten', 'NAS-Grundeinrichtung', 'VLAN und erweiterte Konfiguration', 'Netzwerk dokumentieren', 'Firmware aktualisieren'], 'Sie erhalten eine getestete Netzwerkkonfiguration, klare Zugriffsregeln und Empfehlungen für verbleibende Abdeckungs- oder Hardwarefragen.', 'Feste Verkabelung, Bohren, Montage, Kabelzertifizierung, Elektroarbeiten und Arbeiten an 230 V werden nicht angeboten.'),
    'business-it': c('IT für kleine Unternehmen', 'Verständliche Arbeitsplatz-, E-Mail- und Cloud-Unterstützung für Selbstständige und kleine Betriebe.', 'TiLADYS richtet die digitalen Werkzeuge ein, die kleine Unternehmen täglich benötigen – ohne unnötige Konzernkomplexität. Dazu gehören professionelle E-Mail, gemeinsame Dateien, Besprechungen, Arbeitsplätze und Dokumentation.', ['Professionelle Domain-E-Mail', 'Microsoft 365 einrichten', 'Google Workspace einrichten', 'E-Mail-Migration', 'OneDrive, Google Drive oder Dropbox', 'Gemeinsame Ordner und Berechtigungen', 'Teams, Zoom oder Google Meet', 'Neuen Arbeitsplatz einrichten', 'IT-Inventar und Dokumentation', 'Laufende IT-Support-Pakete'], 'Ihr Team erhält eine praktische, geordnete Einrichtung mit dokumentierten Zugriffsrechten und wichtigen Abläufen.', 'Lizenzen und Drittanbieter-Abos kosten extra. Verfügbarkeit und Migrationsdauer externer Anbieter können nicht garantiert werden.'),
    websites: c('Website-Service', 'Professionelle Websites, Landingpages, Hosting und laufende Betreuung für kleine Unternehmen.', 'TiLADYS plant und erstellt praktische Websites für Smartphone, Tablet und Desktop. Sie wählen zwischen einer Website im Abonnement mit laufender Betreuung und einer Website zum einmaligen Kauf mit vollem Eigentum – zwei getrennte Angebote mit eigener Preisstruktur. Bestehende Websites können überarbeitet und betreut werden.', ['Website-Beratung und Planung', 'Website-Abonnement beziehungsweise Miete', 'Onepage- und Unternehmenswebsites', 'Individuelle Websites und Landingpages', 'Einfache Onlineshops', 'Redesign und mobile Optimierung', 'Formulare und Buchungssysteme', 'Mehrsprachigkeit und Basis-SEO', 'Domain, Hosting und SSL', 'Wartung, Aktualisierung und Inhalte'], 'Sie erhalten eine getestete Website im vereinbarten Umfang; Eigentum, Hosting und laufende Aufgaben werden vorab eindeutig erklärt.', 'Suchpositionen, Besucherzahlen und Ergebnisse externer Integrationen können nicht garantiert werden. Barrierefreiheitsverbesserungen sind kein zertifiziertes Audit.'),
    'google-business': c('Google Business & lokale Sichtbarkeit', 'Ein vollständiges Unternehmensprofil mit korrekten, hilfreichen Informationen für Kunden.', 'TiLADYS unterstützt kleine lokale Unternehmen bei Einrichtung, Prüfung und Pflege ihres Google-Unternehmensprofils. Im Mittelpunkt stehen korrekte Angaben, nützliche Inhalte und ein stimmiger lokaler Auftritt.', ['Profil erstellen und einrichten', 'Bestehendes Profil prüfen', 'Kategorien und Beschreibung', 'Kontakt- und Leistungsangaben', 'Unternehmensfotos', 'Google-Beiträge', 'Vorlagen für Bewertungsantworten', 'QR-Code für Bewertungen', 'Lokale Sichtbarkeit prüfen', 'Verzeichniseinträge abgleichen'], 'Ihr Profil wird vollständiger, konsistenter und für Kunden leichter verständlich.', 'Google entscheidet über Verifizierung, Ranking, Maps-Platzierung und Bewertungen. Diese Ergebnisse und Kundenzahlen können nicht garantiert werden.'),
    'business-photography': c('Business-Fotografie', 'Klare, praktische Fotos für Websites, Profile, Produkte und Unternehmenskommunikation.', 'TiLADYS erstellt fokussierte visuelle Inhalte für kleine Unternehmen und digitale Profile. Die Aufnahmen sind für den praktischen Einsatz auf Website, Google Business und Social Media ausgelegt.', ['Mini-Business-Fotoshooting', 'Reguläres Business-Fotoshooting', 'Website-Fotografie', 'Google-Business-Fotografie', 'Einfache Produktfotografie', 'Kundenfotos bearbeiten', 'Bilder für Websites skalieren', 'Formate für Social Media exportieren'], 'Sie erhalten bearbeitete Bilder in passenden Formaten für die vereinbarten digitalen Kanäle.', 'Aufwendige Studioproduktionen und spezialisierte Produktfotografie außerhalb des TiLADYS-Angebots benötigen einen anderen Anbieter.'),
    'digital-design': c('Digitales Design & Geschäftsmaterialien', 'Nützliche Markenmaterialien für die tägliche Kommunikation online und im Druck.', 'TiLADYS gestaltet wichtige Geschäftsinformationen klar und einheitlich. Der Fokus liegt auf praktischen Materialien, die Kunden und kleine Teams sofort verwenden können.', ['Geschäftliche Social-Profile einrichten', 'Professionelle E-Mail-Signaturen', 'Digitale Visitenkarten', 'QR-Codes', 'Visitenkarten gestalten', 'Leistungs- und Preislisten gestalten', 'Einfaches Brand-Kit', 'Digitale Kataloge und Speisekarten', 'Onlineformulare', 'Einfache No-Code-Automatisierung'], 'Sie erhalten einsatzbereite Dateien oder konfigurierte digitale Werkzeuge in den vereinbarten Formaten.', 'Druckproduktion, umfassende Markenstrategie und individuelle Softwareentwicklung sind getrennte Leistungen.'),
    'training-consulting': c('Schulung & Beratung', 'Freundliche Hilfe bei Computernutzung, Kaufentscheidungen und digitalen Fragen im kleinen Unternehmen.', 'Sie benötigen kein technisches Vorwissen. TiLADYS bietet individuelle oder kleine Gruppenschulungen, praktische Kaufberatung und verständliche schriftliche Anleitungen passend zu Ihrer Situation.', ['Individuelle Computerschulung', 'Computerschulung für kleine Teams', 'PC- und Laptop-Kaufberatung', 'Digitalisierungsberatung für kleine Unternehmen', 'Schriftliche Schritt-für-Schritt-Anleitung', 'Geräteabholung und Lieferung in Mülheim', 'Unterstützung beim Gerätekauf'], 'Sie erhalten klare nächste Schritte, praktisches Wissen oder einen fundierten Kaufplan passend zu Bedarf und Budget.', 'Die Beratung ist technisch und praktisch, aber keine Rechts-, Steuer- oder zertifizierte Datenschutzberatung. Fahrt und Geräte können extra kosten.'),
  },
  uk: {},
  ru: {},
  sk: {},
  fr: {},
};

const localizedTitles: Record<Exclude<Locale, 'en' | 'de'>, Record<string, string>> = {
  uk: { 'it-support-diagnostics': 'IT-підтримка та діагностика', 'pc-laptop': 'Послуги для ПК і ноутбуків', security: 'Безпека та захист облікових записів', 'data-backup': 'Дані та резервні копії', 'pc-cleaning-upgrades': 'Чищення та модернізація ПК', 'network-wifi': 'Мережа та Wi-Fi', 'business-it': 'IT для малого бізнесу', websites: 'Вебсайти', 'google-business': 'Google Business і локальна видимість', 'business-photography': 'Фотографія для бізнесу', 'digital-design': 'Цифровий дизайн', 'training-consulting': 'Навчання та консультації' },
  ru: { 'it-support-diagnostics': 'IT-поддержка и диагностика', 'pc-laptop': 'Услуги для ПК и ноутбуков', security: 'Безопасность и защита аккаунтов', 'data-backup': 'Данные и резервные копии', 'pc-cleaning-upgrades': 'Чистка и модернизация ПК', 'network-wifi': 'Сеть и Wi-Fi', 'business-it': 'IT для малого бизнеса', websites: 'Веб-сайты', 'google-business': 'Google Business и локальная видимость', 'business-photography': 'Фотография для бизнеса', 'digital-design': 'Цифровой дизайн', 'training-consulting': 'Обучение и консультации' },
  sk: { 'it-support-diagnostics': 'IT podpora a diagnostika', 'pc-laptop': 'Služby pre PC a notebooky', security: 'Bezpečnosť a ochrana účtov', 'data-backup': 'Dáta a zálohovanie', 'pc-cleaning-upgrades': 'Čistenie a vylepšenia PC', 'network-wifi': 'Sieť a Wi-Fi', 'business-it': 'IT pre malé firmy', websites: 'Webové stránky', 'google-business': 'Google Business a lokálna viditeľnosť', 'business-photography': 'Firemná fotografia', 'digital-design': 'Digitálny dizajn', 'training-consulting': 'Školenia a poradenstvo' },
  fr: { 'it-support-diagnostics': 'Assistance IT et diagnostic', 'pc-laptop': 'Services PC et ordinateur portable', security: 'Sécurité et protection des comptes', 'data-backup': 'Données et sauvegarde', 'pc-cleaning-upgrades': 'Nettoyage et mises à niveau PC', 'network-wifi': 'Réseau et Wi-Fi', 'business-it': 'IT pour petites entreprises', websites: 'Services de sites web', 'google-business': 'Google Business et visibilité locale', 'business-photography': 'Photographie professionnelle', 'digital-design': 'Design numérique', 'training-consulting': 'Formation et conseil' },
};

const translatedContentIds = ['it-support-diagnostics', 'pc-laptop', 'data-backup', 'network-wifi', 'business-it', 'websites', 'google-business', 'business-photography', 'digital-design'] as const;
for (const locale of ['uk', 'ru', 'sk', 'fr'] as const) {
  for (const id of translatedContentIds) {
    const detail = translatedServiceContent[locale][id];
    localized[locale][id] = [
      localizedTitles[locale][id], detail.short,
      `${detail.short} ${locale === 'uk' ? 'TiLADYS пояснює можливості зрозумілою мовою та погоджує наступні кроки.' : locale === 'ru' ? 'TiLADYS объясняет варианты понятным языком и согласовывает следующие шаги.' : locale === 'sk' ? 'TiLADYS vysvetlí možnosti zrozumiteľne a dohodne s vami ďalší postup.' : 'TiLADYS explique clairement les options et convient avec vous des prochaines étapes.'}`,
      detail.examples,
      locale === 'uk' ? 'Робота виконується в погодженому обсязі, результат перевіряється, а ви отримуєте зрозуміле пояснення.' : locale === 'ru' ? 'Работа выполняется в согласованном объёме, результат проверяется, а вы получаете понятное объяснение.' : locale === 'sk' ? 'Práca sa vykoná v dohodnutom rozsahu, výsledok sa otestuje a dostanete zrozumiteľné vysvetlenie.' : 'Le travail est réalisé selon le périmètre convenu, le résultat est testé et vous recevez une explication claire.',
      detail.limitation,
    ];
  }
}

const pcLaptopGroups: Record<Locale, Array<{ title: string; items: string[] }>> = {
  en: [
    { title: 'Setup & Software', items: ['New PC or laptop setup', 'Windows or Linux installation', 'Software and Microsoft Office setup', 'Email, printer and scanner setup', 'Updates, optimization and startup troubleshooting'] },
    { title: 'Cleaning & Maintenance', items: ['Desktop or laptop internal cleaning', 'Thermal-paste replacement', 'Cooling inspection', 'Temperature and stability testing'] },
    { title: 'Modular Upgrades', items: ['RAM, SSD or HDD installation', 'Graphics card or PCIe-card installation', 'Modular power-supply replacement', 'Fan or cooler replacement', 'Storage upgrade with system transfer'] },
    { title: 'PC Building', items: ['Office PC assembly', 'Gaming or performance PC assembly', 'Component compatibility and selection', 'BIOS setup', 'Final stability and temperature testing'] },
  ],
  de: [
    { title: 'Einrichtung & Software', items: ['Neuen PC oder Laptop einrichten', 'Windows oder Linux installieren', 'Programme und Microsoft Office einrichten', 'E-Mail, Drucker und Scanner einrichten', 'Updates, Optimierung und Startfehler beheben'] },
    { title: 'Reinigung & Wartung', items: ['Desktop-PC oder Laptop innen reinigen', 'Wärmeleitpaste erneuern', 'Kühlung prüfen', 'Temperatur und Stabilität testen'] },
    { title: 'Modulare Upgrades', items: ['RAM, SSD oder HDD einbauen', 'Grafikkarte oder PCIe-Karte einbauen', 'Modulares Netzteil austauschen', 'Lüfter oder Kühler austauschen', 'Datenträger-Upgrade mit Systemübertragung'] },
    { title: 'PC-Zusammenbau', items: ['Office-PC zusammenbauen', 'Gaming- oder Performance-PC zusammenbauen', 'Kompatibilität und Komponentenauswahl', 'BIOS einrichten', 'Abschließender Stabilitäts- und Temperaturtest'] },
  ],
  uk: [
    { title: 'Налаштування та програми', items: ['Налаштування нового ПК або ноутбука', 'Встановлення Windows або Linux', 'Програми та Microsoft Office', 'Пошта, принтер і сканер', 'Оновлення, оптимізація та помилки запуску'] },
    { title: 'Чищення та обслуговування', items: ['Внутрішнє чищення ПК або ноутбука', 'Заміна термопасти', 'Перевірка охолодження', 'Тест температур і стабільності'] },
    { title: 'Модульна модернізація', items: ['Встановлення RAM, SSD або HDD', 'Відеокарта або PCIe-карта', 'Заміна модульного блока живлення', 'Заміна вентилятора або кулера', 'Новий накопичувач із перенесенням системи'] },
    { title: 'Складання ПК', items: ['Складання офісного ПК', 'Складання ігрового або продуктивного ПК', 'Перевірка сумісності й вибір компонентів', 'Налаштування BIOS', 'Фінальний тест температур і стабільності'] },
  ],
  ru: [
    { title: 'Настройка и программы', items: ['Настройка нового ПК или ноутбука', 'Установка Windows или Linux', 'Программы и Microsoft Office', 'Почта, принтер и сканер', 'Обновления, оптимизация и ошибки запуска'] },
    { title: 'Чистка и обслуживание', items: ['Внутренняя чистка ПК или ноутбука', 'Замена термопасты', 'Проверка охлаждения', 'Тест температур и стабильности'] },
    { title: 'Модульные улучшения', items: ['Установка RAM, SSD или HDD', 'Видеокарта или PCIe-карта', 'Замена модульного блока питания', 'Замена вентилятора или кулера', 'Новый накопитель с переносом системы'] },
    { title: 'Сборка ПК', items: ['Сборка офисного ПК', 'Сборка игрового или производительного ПК', 'Проверка совместимости и подбор компонентов', 'Настройка BIOS', 'Финальный тест температур и стабильности'] },
  ],
  sk: [
    { title: 'Nastavenie a softvér', items: ['Nastavenie nového PC alebo notebooku', 'Inštalácia Windows alebo Linuxu', 'Softvér a Microsoft Office', 'E-mail, tlačiareň a skener', 'Aktualizácie, optimalizácia a chyby spustenia'] },
    { title: 'Čistenie a údržba', items: ['Vnútorné čistenie PC alebo notebooku', 'Výmena teplovodivej pasty', 'Kontrola chladenia', 'Test teplôt a stability'] },
    { title: 'Modulárne vylepšenia', items: ['Montáž RAM, SSD alebo HDD', 'Grafická alebo PCIe karta', 'Výmena modulárneho zdroja', 'Výmena ventilátora alebo chladiča', 'Nový disk s prenosom systému'] },
    { title: 'Skladanie PC', items: ['Zostavenie kancelárskeho PC', 'Zostavenie herného alebo výkonného PC', 'Kompatibilita a výber komponentov', 'Nastavenie BIOS', 'Záverečný test teplôt a stability'] },
  ],
  fr: [
    { title: 'Configuration et logiciels', items: ['Configuration d’un nouveau PC ou portable', 'Installation de Windows ou Linux', 'Logiciels et Microsoft Office', 'E-mail, imprimante et scanner', 'Mises à jour, optimisation et démarrage'] },
    { title: 'Nettoyage et entretien', items: ['Nettoyage interne PC ou portable', 'Remplacement de pâte thermique', 'Contrôle du refroidissement', 'Tests de température et stabilité'] },
    { title: 'Mises à niveau modulaires', items: ['Installation RAM, SSD ou HDD', 'Carte graphique ou PCIe', 'Remplacement d’alimentation modulaire', 'Remplacement de ventilateur ou refroidisseur', 'Nouveau stockage avec transfert du système'] },
    { title: 'Assemblage de PC', items: ['Assemblage d’un PC bureautique', 'Assemblage d’un PC gaming ou performant', 'Compatibilité et choix des composants', 'Configuration du BIOS', 'Test final de température et stabilité'] },
  ],
};

const pcLaptopMergedCopy: Record<Locale, { short: string; intro: string; expected: string; limitations: string }> = {
  en: { short: 'Setup, software, cleaning, modular upgrades and PC building in one practical service.', intro: 'TiLADYS supports the complete everyday lifecycle of PCs and laptops: getting a new device ready, solving software problems, cleaning cooling systems, installing compatible upgrades and assembling a new computer. The work is organized into clear areas so you can quickly find the help you need.', expected: 'Your computer is configured, cleaned, upgraded or assembled for the agreed purpose, then tested for stable operation and explained clearly at handover.', limitations: 'Components and licences are separate unless agreed otherwise. Board-level electronics repair, soldering, display electronics repair and power-supply electronics repair are not offered.' },
  de: { short: 'Einrichtung, Software, Reinigung, modulare Upgrades und PC-Zusammenbau aus einer Hand.', intro: 'TiLADYS unterstützt den gesamten praktischen Alltag von PCs und Laptops: neue Geräte einrichten, Softwareprobleme lösen, Kühlsysteme reinigen, kompatible Upgrades einbauen und neue Computer zusammenstellen. Klare Bereiche helfen Ihnen, schnell die passende Leistung zu finden.', expected: 'Ihr Computer wird für den vereinbarten Zweck eingerichtet, gereinigt, aufgerüstet oder zusammengebaut, anschließend auf stabilen Betrieb geprüft und verständlich erklärt.', limitations: 'Komponenten und Lizenzen kosten extra, sofern nicht anders vereinbart. Reparaturen auf Platinenebene, Lötarbeiten sowie Reparaturen an Display- oder Netzteilelektronik werden nicht angeboten.' },
  uk: { short: 'Налаштування, програми, чищення, модульна модернізація та складання ПК в одній практичній послузі.', intro: 'TiLADYS допомагає на всіх основних етапах роботи з ПК і ноутбуком: налаштовує нові пристрої, вирішує програмні проблеми, чистить охолодження, встановлює сумісні компоненти та складає нові комп’ютери. Послуги поділені на зрозумілі розділи.', expected: 'Комп’ютер налаштовується, очищується, модернізується або складається для погодженої мети, після чого перевіряється його стабільна робота.', limitations: 'Компоненти й ліцензії оплачуються окремо. Ремонт плат, паяння, ремонт електроніки дисплеїв і блоків живлення не виконуються.' },
  ru: { short: 'Настройка, программы, чистка, модульные улучшения и сборка ПК в одной практической услуге.', intro: 'TiLADYS помогает на всех основных этапах работы с ПК и ноутбуком: настраивает новые устройства, решает программные проблемы, чистит охлаждение, устанавливает совместимые компоненты и собирает новые компьютеры. Услуги разделены на понятные направления.', expected: 'Компьютер настраивается, очищается, модернизируется или собирается для согласованной задачи, после чего проверяется стабильность его работы.', limitations: 'Компоненты и лицензии оплачиваются отдельно. Ремонт плат, пайка, ремонт электроники дисплеев и блоков питания не выполняются.' },
  sk: { short: 'Nastavenie, softvér, čistenie, modulárne vylepšenia a skladanie PC v jednej praktickej službe.', intro: 'TiLADYS pomáha počas celého bežného životného cyklu PC a notebooku: nastaví nové zariadenie, vyrieši softvérové problémy, vyčistí chladenie, namontuje kompatibilné komponenty a zostaví nový počítač. Služby sú rozdelené do jasných oblastí.', expected: 'Počítač sa nastaví, vyčistí, vylepší alebo zostaví na dohodnutý účel a následne sa otestuje jeho stabilná prevádzka.', limitations: 'Komponenty a licencie sa platia osobitne. Opravy dosiek, spájkovanie ani opravy elektroniky displejov a zdrojov sa neposkytujú.' },
  fr: { short: 'Configuration, logiciels, nettoyage, mises à niveau modulaires et assemblage PC dans un même service pratique.', intro: 'TiLADYS accompagne le cycle de vie courant des PC et portables : préparation d’un nouvel appareil, résolution de problèmes logiciels, nettoyage du refroidissement, installation de composants compatibles et assemblage d’un nouvel ordinateur. Les services sont organisés en domaines clairs.', expected: 'Votre ordinateur est configuré, nettoyé, amélioré ou assemblé selon l’objectif convenu, puis testé pour vérifier son fonctionnement stable.', limitations: 'Les composants et licences sont facturés séparément. La réparation électronique des cartes, la soudure et la réparation de l’électronique des écrans ou alimentations ne sont pas proposées.' },
};

const groupTitles: Record<Locale, { pcData: string; web: string[]; business: string[] }> = {
  en: { pcData: 'Data & Backup', web: ['Website Creation', 'Website Subscription / Rental', 'Website Improvements', 'SEO & Technical Setup', 'Website Support'], business: ['Business IT Setup', 'Wi-Fi & Network', 'Business Data & Cloud', 'Google Business & Local Visibility', 'Business Photography', 'Business Design & Digital Materials'] },
  de: { pcData: 'Daten & Backup', web: ['Website-Erstellung', 'Website-Abonnement / Miete', 'Website-Verbesserungen', 'SEO & technische Einrichtung', 'Website-Support'], business: ['Business-IT-Einrichtung', 'WLAN & Netzwerk', 'Geschäftsdaten & Cloud', 'Google Business & lokale Sichtbarkeit', 'Business-Fotografie', 'Business-Design & digitale Materialien'] },
  uk: { pcData: 'Дані та резервні копії', web: ['Створення сайтів', 'Підписка / оренда сайту', 'Покращення сайту', 'SEO й технічне налаштування', 'Підтримка сайту'], business: ['Налаштування IT для бізнесу', 'Wi-Fi і мережа', 'Дані та хмара для бізнесу', 'Google Business і локальна видимість', 'Фотографія для бізнесу', 'Дизайн і цифрові матеріали'] },
  ru: { pcData: 'Данные и резервные копии', web: ['Создание сайтов', 'Подписка / аренда сайта', 'Улучшение сайта', 'SEO и техническая настройка', 'Поддержка сайта'], business: ['Настройка IT для бизнеса', 'Wi-Fi и сеть', 'Данные и облако для бизнеса', 'Google Business и локальная видимость', 'Фотография для бизнеса', 'Дизайн и цифровые материалы'] },
  sk: { pcData: 'Dáta a zálohovanie', web: ['Tvorba webových stránok', 'Predplatné / prenájom webu', 'Vylepšenia webu', 'SEO a technické nastavenie', 'Podpora webu'], business: ['Nastavenie firemného IT', 'Wi-Fi a sieť', 'Firemné dáta a cloud', 'Google Business a lokálna viditeľnosť', 'Firemná fotografia', 'Dizajn a digitálne materiály'] },
  fr: { pcData: 'Données et sauvegarde', web: ['Création de sites web', 'Abonnement / location de site', 'Amélioration de site', 'SEO et configuration technique', 'Assistance du site'], business: ['Configuration IT professionnelle', 'Wi-Fi et réseau', 'Données et cloud professionnels', 'Google Business et visibilité locale', 'Photographie professionnelle', 'Design et supports numériques'] },
};

const consolidatedCopy: Record<Locale, Record<ServiceId, { title: string; short: string; intro: string; expected: string; limitations?: string }>> = {
  en: {
    'pc-laptop': { title: 'PC & Laptop Services', ...pcLaptopMergedCopy.en, short: 'Computer setup, troubleshooting, cleaning, upgrades, PC building and personal data services.' },
    websites: { title: 'Website Creation & Web Services', short: 'Professional websites for local businesses, self-employed professionals and growing projects.', intro: 'TiLADYS creates practical, responsive websites and supports them after launch. Website subscriptions and purchased websites are separate options, with scope, ownership, hosting and ongoing responsibilities explained clearly before work starts.', expected: 'You receive a tested website solution matched to the agreed goals, devices and support model.', limitations: localized.en.websites[5] ?? '' },
    'business-it': { title: 'Business IT & Digital Services', short: 'Practical IT and digital support for self-employed professionals and small businesses.', intro: 'TiLADYS brings everyday business technology into one clear service: workplace setup, email and cloud, Wi-Fi, backups, local visibility, photography and useful digital materials.', expected: 'Your business receives a practical setup or finished digital asset, with the agreed work tested, organized and explained.', limitations: 'Licences and third-party subscriptions are separate. Network work excludes structural cabling, drilling, electrical work and cable certification. Search rankings and third-party verification cannot be guaranteed.' },
  },
  de: {
    'pc-laptop': { title: 'PC- & Laptop-Service', ...pcLaptopMergedCopy.de, short: 'Computer-Einrichtung, Fehlerbehebung, Reinigung, Upgrades, PC-Zusammenbau und persönliche Datenservices.' },
    websites: { title: 'Website-Erstellung & Webservices', short: 'Professionelle Websites für lokale Unternehmen, Selbstständige und wachsende Projekte.', intro: 'TiLADYS erstellt praktische, responsive Websites und unterstützt sie nach dem Start. Website-Abonnements und gekaufte Websites sind getrennte Modelle; Umfang, Eigentum, Hosting und laufende Betreuung werden vorab verständlich erklärt.', expected: 'Sie erhalten eine getestete Website-Lösung, die zu den vereinbarten Zielen, Geräten und dem gewählten Betreuungsmodell passt.', limitations: localized.de.websites[5] ?? '' },
    'business-it': { title: 'Business-IT & digitale Services', short: 'Praktische IT- und digitale Unterstützung für Selbstständige und kleine Unternehmen.', intro: 'TiLADYS bündelt die alltägliche Unternehmenstechnik in einem klaren Service: Arbeitsplatz, E-Mail und Cloud, WLAN, Backups, lokale Sichtbarkeit, Fotografie und nützliche digitale Materialien.', expected: 'Ihr Unternehmen erhält eine praktische Einrichtung oder ein fertiges digitales Ergebnis; die vereinbarten Arbeiten werden geprüft, geordnet und verständlich erklärt.', limitations: 'Lizenzen und Abonnements kosten extra. Netzwerkarbeiten umfassen keine feste Verkabelung, Bohrungen, Elektroarbeiten oder Kabelzertifizierung. Rankings und Prüfungen durch Drittanbieter können nicht garantiert werden.' },
  },
  uk: {
    'pc-laptop': { title: 'Послуги для ПК і ноутбуків', ...pcLaptopMergedCopy.uk, short: 'Налаштування, діагностика, чищення, модернізація, складання ПК та допомога з особистими даними.' },
    websites: { title: 'Створення сайтів і вебпослуги', short: 'Професійні сайти для локального бізнесу, самозайнятих і проєктів, що розвиваються.', intro: 'TiLADYS створює практичні адаптивні сайти й підтримує їх після запуску. Підписка на сайт і купівля сайту — окремі моделі; обсяг, власність, хостинг і подальша підтримка пояснюються заздалегідь.', expected: 'Ви отримуєте перевірений сайт відповідно до погоджених цілей, пристроїв і моделі підтримки.', limitations: localized.uk.websites[5] ?? '' },
    'business-it': { title: 'IT і цифрові послуги для бізнесу', short: 'Практична IT- та цифрова підтримка для самозайнятих і малого бізнесу.', intro: 'TiLADYS об’єднує щоденні цифрові завдання бізнесу: робочі місця, пошту й хмару, Wi-Fi, резервні копії, локальну видимість, фотографію та корисні цифрові матеріали.', expected: 'Бізнес отримує практичне налаштування або готовий цифровий матеріал із перевіркою та зрозумілим поясненням.', limitations: 'Ліцензії й підписки оплачуються окремо. Не виконуються прокладання кабелів, свердління, електромонтаж і сертифікація. Позиції та перевірка сторонніми сервісами не гарантуються.' },
  },
  ru: {
    'pc-laptop': { title: 'Услуги для ПК и ноутбуков', ...pcLaptopMergedCopy.ru, short: 'Настройка, диагностика, чистка, модернизация, сборка ПК и помощь с личными данными.' },
    websites: { title: 'Создание сайтов и веб-услуги', short: 'Профессиональные сайты для локального бизнеса, самозанятых и развивающихся проектов.', intro: 'TiLADYS создаёт практичные адаптивные сайты и поддерживает их после запуска. Подписка и покупка сайта — разные модели; объём, владение, хостинг и дальнейшая поддержка объясняются заранее.', expected: 'Вы получаете проверенный сайт в соответствии с согласованными целями, устройствами и моделью поддержки.', limitations: localized.ru.websites[5] ?? '' },
    'business-it': { title: 'IT и цифровые услуги для бизнеса', short: 'Практичная IT- и цифровая поддержка для самозанятых и малого бизнеса.', intro: 'TiLADYS объединяет повседневные цифровые задачи бизнеса: рабочие места, почту и облако, Wi-Fi, резервные копии, локальную видимость, фотографию и полезные цифровые материалы.', expected: 'Бизнес получает практичную настройку или готовый цифровой материал с проверкой и понятным объяснением.', limitations: 'Лицензии и подписки оплачиваются отдельно. Не выполняются прокладка кабелей, сверление, электромонтаж и сертификация. Позиции и проверка сторонними сервисами не гарантируются.' },
  },
  sk: {
    'pc-laptop': { title: 'Služby pre PC a notebooky', ...pcLaptopMergedCopy.sk, short: 'Nastavenie, diagnostika, čistenie, vylepšenia, skladanie PC a pomoc s osobnými dátami.' },
    websites: { title: 'Tvorba webov a webové služby', short: 'Profesionálne weby pre lokálne firmy, živnostníkov a rastúce projekty.', intro: 'TiLADYS tvorí praktické responzívne weby a podporuje ich aj po spustení. Predplatné a kúpa webu sú samostatné modely; rozsah, vlastníctvo, hosting a ďalšia podpora sa vysvetlia vopred.', expected: 'Dostanete otestované webové riešenie podľa dohodnutých cieľov, zariadení a modelu podpory.', limitations: localized.sk.websites[5] ?? '' },
    'business-it': { title: 'Firemné IT a digitálne služby', short: 'Praktická IT a digitálna podpora pre živnostníkov a malé firmy.', intro: 'TiLADYS spája bežné digitálne potreby firmy: pracoviská, e-mail a cloud, Wi-Fi, zálohy, lokálnu viditeľnosť, fotografiu a užitočné digitálne materiály.', expected: 'Firma dostane praktické nastavenie alebo hotový digitálny výstup, ktorý je skontrolovaný a zrozumiteľne vysvetlený.', limitations: 'Licencie a predplatné sa platia osobitne. Nevykonáva sa kabeláž, vŕtanie, elektroinštalácia ani certifikácia. Poradie a overenie tretími stranami nemožno zaručiť.' },
  },
  fr: {
    'pc-laptop': { title: 'Services PC et ordinateur portable', ...pcLaptopMergedCopy.fr, short: 'Configuration, diagnostic, nettoyage, mises à niveau, assemblage PC et aide pour les données personnelles.' },
    websites: { title: 'Création de sites et services web', short: 'Sites professionnels pour entreprises locales, indépendants et projets en développement.', intro: 'TiLADYS crée des sites pratiques et responsifs, puis les accompagne après leur lancement. L’abonnement et l’achat d’un site sont deux modèles distincts ; périmètre, propriété, hébergement et suivi sont expliqués à l’avance.', expected: 'Vous recevez un site testé, adapté aux objectifs, appareils et au modèle d’assistance convenus.', limitations: localized.fr.websites[5] ?? '' },
    'business-it': { title: 'IT et services numériques pour entreprises', short: 'Assistance IT et numérique pratique pour indépendants et petites entreprises.', intro: 'TiLADYS réunit les besoins numériques quotidiens : postes de travail, e-mail et cloud, Wi-Fi, sauvegardes, visibilité locale, photographie et supports numériques utiles.', expected: 'Votre entreprise reçoit une configuration pratique ou un support numérique finalisé, vérifié et clairement expliqué.', limitations: 'Licences et abonnements sont séparés. Le câblage structurel, le perçage, l’électricité et la certification sont exclus. Le classement et la vérification par des tiers ne sont pas garantis.' },
  },
};

function consolidatedGroups(id: ServiceId, locale: Locale) {
  const titles = groupTitles[locale];
  if (id === 'pc-laptop') return [...pcLaptopGroups[locale], { title: titles.pcData, items: localized[locale]['data-backup'][3].slice(0, 7) }];
  if (id === 'websites') {
    const items = localized[locale].websites[3];
    return titles.web.map((title, index) => ({ title, items: index === 0 ? items.slice(2, 5) : index === 1 ? items.slice(1, 2) : index === 2 ? items.slice(5, 8) : index === 3 ? items.slice(7, 9) : items.slice(8, 10) }));
  }
  const sources = ['business-it', 'network-wifi', 'data-backup', 'google-business', 'business-photography', 'digital-design'];
  return titles.business.map((title, index) => ({ title, items: localized[locale][sources[index]][3].slice(0, index < 3 ? 7 : 6) }));
}

export function serviceCopy(id: ServiceId, locale: string): ServiceCopy {
  const selectedLocale = Object.prototype.hasOwnProperty.call(pcLaptopGroups, locale) ? locale as Locale : 'en';
  const copy = consolidatedCopy[selectedLocale][id];
  const groups = consolidatedGroups(id, selectedLocale);
  return { ...copy, intro: [copy.intro], examples: groups.flatMap((group) => group.items), groups, metaTitle: copy.title, metaDescription: copy.short };
}

export const servicesUi: Record<Locale, {
  nav: string; breadcrumb: string; heroTitle: string; heroText: string; explore: string; contact: string;
  from: string; pricingUnavailable: string; disclaimer: string; examples: string; expected: string;
  important: string; processTitle: string; process: string[]; related: string; request: string; ask: string;
  notSureTitle: string; notSureText: string; describe: string; finalTitle: string; finalText: string;
}> = {
  en: { nav: 'Services', breadcrumb: 'Services', heroTitle: 'IT, Websites & Digital Services', heroText: 'Practical technical and digital support for private customers, self-employed professionals and small businesses in Mülheim an der Ruhr and across NRW.', explore: 'Explore services', contact: 'Contact TiLADYS', from: 'From', pricingUnavailable: 'Price on request', disclaimer: 'The final price depends on the device, problem, scope, required components and individual circumstances. Any additional work or costs are discussed with you before we proceed.', examples: 'What we can help with', expected: 'What you can expect', important: 'Important information', processTitle: 'How it works', process: ['Tell us what you need', 'We review the situation', 'You receive an estimate', 'We complete the work', 'We test the result', 'You receive the finished service'], related: 'Related services', request: 'Request this service', ask: 'Ask a question', notSureTitle: 'Not sure which service you need?', notSureText: 'You do not need to diagnose the problem yourself. Describe what is happening and TiLADYS will help determine the right solution.', describe: 'Describe your problem', finalTitle: 'Need help with this service?', finalText: 'Tell us what you need and we will recommend the right solution.' },
  de: { nav: 'Services', breadcrumb: 'Services', heroTitle: 'IT, Websites & digitale Services', heroText: 'Praktische technische und digitale Unterstützung für Privatkunden, Selbstständige und kleine Unternehmen in Mülheim an der Ruhr und NRW.', explore: 'Services entdecken', contact: 'TiLADYS kontaktieren', from: 'Ab', pricingUnavailable: 'Preis auf Anfrage', disclaimer: 'Der endgültige Preis hängt vom Gerät, Problem, Arbeitsumfang, benötigten Komponenten und der individuellen Situation ab. Zusätzliche Arbeiten oder Kosten werden vorab mit Ihnen besprochen.', examples: 'Wobei wir helfen können', expected: 'Was Sie erwarten können', important: 'Wichtige Hinweise', processTitle: 'So funktioniert es', process: ['Sie beschreiben Ihr Anliegen', 'Wir prüfen die Situation', 'Sie erhalten eine Einschätzung', 'Wir führen die Arbeit aus', 'Wir testen das Ergebnis', 'Sie erhalten die fertige Leistung'], related: 'Passende Services', request: 'Diesen Service anfragen', ask: 'Frage stellen', notSureTitle: 'Nicht sicher, welchen Service Sie benötigen?', notSureText: 'Sie müssen das Problem nicht selbst diagnostizieren. Beschreiben Sie einfach, was passiert – TiLADYS hilft, die passende Lösung zu finden.', describe: 'Problem beschreiben', finalTitle: 'Benötigen Sie Hilfe mit diesem Service?', finalText: 'Beschreiben Sie Ihr Anliegen und wir empfehlen die passende Lösung.' },
  uk: { nav: 'Послуги', breadcrumb: 'Послуги', heroTitle: 'IT, вебсайти та цифрові послуги', heroText: 'Практична технічна й цифрова підтримка для приватних клієнтів, самозайнятих і малого бізнесу в Мюльгаймі-на-Рурі та NRW.', explore: 'Переглянути послуги', contact: 'Зв’язатися з TiLADYS', from: 'Від', pricingUnavailable: 'Ціна за запитом', disclaimer: 'Кінцева ціна залежить від пристрою, проблеми, обсягу робіт, потрібних компонентів та індивідуальних обставин. Додаткові роботи або витрати завжди узгоджуються заздалегідь.', examples: 'З чим ми можемо допомогти', expected: 'Якого результату очікувати', important: 'Важлива інформація', processTitle: 'Як це працює', process: ['Опишіть, що вам потрібно', 'Ми розглянемо ситуацію', 'Ви отримаєте оцінку', 'Ми виконаємо роботу', 'Ми перевіримо результат', 'Ви отримаєте готову послугу'], related: 'Пов’язані послуги', request: 'Замовити цю послугу', ask: 'Поставити запитання', notSureTitle: 'Не впевнені, яка послуга потрібна?', notSureText: 'Вам не потрібно самостійно визначати проблему. Опишіть, що відбувається, і TiLADYS допоможе знайти правильне рішення.', describe: 'Описати проблему', finalTitle: 'Потрібна допомога з цією послугою?', finalText: 'Розкажіть, що вам потрібно, і ми порадимо відповідне рішення.' },
  ru: { nav: 'Услуги', breadcrumb: 'Услуги', heroTitle: 'IT, веб-сайты и цифровые услуги', heroText: 'Практическая техническая и цифровая поддержка для частных клиентов, самозанятых и малого бизнеса в Мюльхайме-на-Руре и NRW.', explore: 'Посмотреть услуги', contact: 'Связаться с TiLADYS', from: 'От', pricingUnavailable: 'Цена по запросу', disclaimer: 'Итоговая цена зависит от устройства, проблемы, объёма работ, необходимых компонентов и индивидуальной ситуации. Дополнительные работы и расходы всегда согласовываются заранее.', examples: 'С чем мы можем помочь', expected: 'Какого результата ожидать', important: 'Важная информация', processTitle: 'Как это работает', process: ['Опишите, что вам нужно', 'Мы рассмотрим ситуацию', 'Вы получите оценку', 'Мы выполним работу', 'Мы проверим результат', 'Вы получите готовую услугу'], related: 'Связанные услуги', request: 'Заказать эту услугу', ask: 'Задать вопрос', notSureTitle: 'Не уверены, какая услуга нужна?', notSureText: 'Вам не нужно самостоятельно определять причину. Опишите, что происходит, и TiLADYS поможет подобрать решение.', describe: 'Описать проблему', finalTitle: 'Нужна помощь с этой услугой?', finalText: 'Расскажите, что вам нужно, и мы предложим подходящее решение.' },
  sk: { nav: 'Služby', breadcrumb: 'Služby', heroTitle: 'IT, webové stránky a digitálne služby', heroText: 'Praktická technická a digitálna podpora pre súkromné osoby, živnostníkov a malé firmy v Mülheime an der Ruhr a NRW.', explore: 'Pozrieť služby', contact: 'Kontaktovať TiLADYS', from: 'Od', pricingUnavailable: 'Cena na vyžiadanie', disclaimer: 'Konečná cena závisí od zariadenia, problému, rozsahu práce, potrebných komponentov a individuálnej situácie. Dodatočné práce alebo náklady s vami vždy vopred prekonzultujeme.', examples: 'S čím vám môžeme pomôcť', expected: 'Čo môžete očakávať', important: 'Dôležité informácie', processTitle: 'Ako to funguje', process: ['Poviete nám, čo potrebujete', 'Posúdime situáciu', 'Dostanete odhad', 'Vykonáme prácu', 'Otestujeme výsledok', 'Dostanete hotovú službu'], related: 'Súvisiace služby', request: 'Požiadať o túto službu', ask: 'Položiť otázku', notSureTitle: 'Neviete, ktorú službu potrebujete?', notSureText: 'Problém nemusíte diagnostikovať sami. Opíšte, čo sa deje, a TiLADYS vám pomôže nájsť správne riešenie.', describe: 'Opísať problém', finalTitle: 'Potrebujete pomoc s touto službou?', finalText: 'Povedzte nám, čo potrebujete, a odporučíme vhodné riešenie.' },
  fr: { nav: 'Services', breadcrumb: 'Services', heroTitle: 'IT, sites web et services numériques', heroText: 'Assistance technique et numérique pratique pour particuliers, indépendants et petites entreprises à Mülheim an der Ruhr et en NRW.', explore: 'Découvrir les services', contact: 'Contacter TiLADYS', from: 'À partir de', pricingUnavailable: 'Prix sur demande', disclaimer: 'Le prix final dépend de l’appareil, du problème, de l’étendue du travail, des composants nécessaires et de votre situation. Tout travail ou coût supplémentaire est discuté avec vous avant intervention.', examples: 'Comment nous pouvons vous aider', expected: 'Ce que vous pouvez attendre', important: 'Informations importantes', processTitle: 'Comment cela fonctionne', process: ['Expliquez votre besoin', 'Nous examinons la situation', 'Vous recevez une estimation', 'Nous réalisons le travail', 'Nous testons le résultat', 'Vous recevez le service terminé'], related: 'Services associés', request: 'Demander ce service', ask: 'Poser une question', notSureTitle: 'Vous ne savez pas quel service choisir ?', notSureText: 'Vous n’avez pas besoin de diagnostiquer le problème vous-même. Décrivez ce qui se passe et TiLADYS vous aidera à trouver la bonne solution.', describe: 'Décrire votre problème', finalTitle: 'Besoin d’aide avec ce service ?', finalText: 'Expliquez votre besoin et nous vous recommanderons la solution adaptée.' },
};

export function ui(locale: string) { return servicesUi[locale as Locale] ?? servicesUi.en; }
export function priceLabel(ref: ServicePriceRef, locale: string) { return ref.label[locale as Locale] ?? ref.label.en; }
