import type { Locale } from '@tiladys/shared';

export const nrwCities = ['Mülheim an der Ruhr', 'Düsseldorf', 'Dortmund', 'Duisburg', 'Oberhausen', 'Wuppertal', 'Essen'];
export const pcServiceArea = [
  { '@type': 'AdministrativeArea', name: 'Nordrhein-Westfalen', alternateName: 'NRW' },
  ...nrwCities.map((name) => ({ '@type': 'City', name })),
];
const copy: Record<Locale, { title: string; description: string; text: string }> = {
  en: { title: 'PC & laptop support in NRW', description: 'PC and laptop cleaning, setup, upgrades and software support in Mülheim an der Ruhr and NRW. Contact TiLADYS to discuss your device and requirements.', text: 'TiLADYS provides PC and laptop services in North Rhine-Westphalia (NRW), including Mülheim an der Ruhr, Düsseldorf, Dortmund, Duisburg, Oberhausen, Wuppertal and Essen. Based in Mülheim an der Ruhr, we serve customers in these cities; they are service areas, not additional offices. Contact us to agree the service scope and arrangements for your location. PC and laptop services are limited to NRW.' },
  de: { title: 'PC- & Laptop-Service in NRW', description: 'PC- und Laptop-Reinigung, Einrichtung, Upgrades und Softwarehilfe in Mülheim an der Ruhr und NRW. Besprechen Sie Ihr Anliegen mit TiLADYS.', text: 'TiLADYS bietet PC- und Laptop-Services in Nordrhein-Westfalen (NRW), darunter Mülheim an der Ruhr, Düsseldorf, Dortmund, Duisburg, Oberhausen, Wuppertal und Essen. Unser Standort ist Mülheim an der Ruhr; die genannten Städte gehören zum Servicegebiet und sind keine weiteren Niederlassungen. Kontaktieren Sie uns, um Leistungsumfang und Ablauf für Ihren Standort abzustimmen. PC- und Laptop-Services sind auf NRW begrenzt.' },
  uk: { title: 'Підтримка ПК і ноутбуків у NRW', description: 'Чищення, налаштування, модернізація ПК і ноутбуків та допомога з програмами в Mülheim an der Ruhr і NRW. Обговоріть своє звернення з TiLADYS.', text: 'TiLADYS надає послуги для ПК і ноутбуків у Північному Рейні-Вестфалії (NRW), зокрема в Mülheim an der Ruhr, Düsseldorf, Dortmund, Duisburg, Oberhausen, Wuppertal та Essen. Ми працюємо з Mülheim an der Ruhr; перелічені міста — територія обслуговування, а не окремі офіси. Зв’яжіться з нами, щоб узгодити обсяг і порядок роботи для вашого місця розташування. Послуги для ПК і ноутбуків обмежені NRW.' },
  ru: { title: 'Поддержка ПК и ноутбуков в NRW', description: 'Чистка, настройка, модернизация ПК и ноутбуков и помощь с программами в Mülheim an der Ruhr и NRW. Обсудите свою задачу с TiLADYS.', text: 'TiLADYS оказывает услуги для ПК и ноутбуков в Северном Рейне-Вестфалии (NRW), включая Mülheim an der Ruhr, Düsseldorf, Dortmund, Duisburg, Oberhausen, Wuppertal и Essen. Мы работаем из Mülheim an der Ruhr; перечисленные города — территория обслуживания, а не дополнительные офисы. Свяжитесь с нами, чтобы согласовать объём и порядок работы для вашего местоположения. Услуги для ПК и ноутбуков ограничены NRW.' },
  sk: { title: 'Podpora PC a notebookov v NRW', description: 'Čistenie, nastavenie, modernizácia PC a notebookov a softvérová pomoc v Mülheim an der Ruhr a NRW. Obráťte sa na TiLADYS so svojou požiadavkou.', text: 'TiLADYS poskytuje služby pre PC a notebooky v Severnom Porýní-Vestfálsku (NRW), vrátane miest Mülheim an der Ruhr, Düsseldorf, Dortmund, Duisburg, Oberhausen, Wuppertal a Essen. Pôsobíme z Mülheim an der Ruhr; uvedené mestá sú oblasťou služieb, nie ďalšími pobočkami. Kontaktujte nás a dohodneme rozsah a postup pre vašu lokalitu. Služby pre PC a notebooky sú obmedzené na NRW.' },
  fr: { title: 'Assistance PC et portables en NRW', description: 'Nettoyage, configuration, mises à niveau et aide logicielle pour PC et portables à Mülheim an der Ruhr et en NRW. Contactez TiLADYS pour votre demande.', text: 'TiLADYS propose des services pour PC et ordinateurs portables en Rhénanie-du-Nord-Westphalie (NRW), notamment à Mülheim an der Ruhr, Düsseldorf, Dortmund, Duisburg, Oberhausen, Wuppertal et Essen. Notre base est à Mülheim an der Ruhr ; les villes citées sont des zones desservies et non des bureaux supplémentaires. Contactez-nous pour convenir des prestations et des modalités selon votre localisation. Les services PC et portables sont limités à la NRW.' },
};
export const serviceAreaCopy = (locale: string) => copy[locale as Locale] ?? copy.en;
