'use client';

import Link from 'next/link';
import { useMemo, useRef, useState } from 'react';
import { ArrowDownToLine, ListPlus, Plus, ReceiptText, Save, Trash2 } from 'lucide-react';

type Customer = { id: string; customerNumber: string; firstName: string | null; lastName: string | null; companyId: string | null; status: string; company: { name: string } | null };
type PriceItem = { id: string; code: string; name: unknown; note: unknown; price: string };
type LineItem = { id?: string; cataloguePriceItemId: string; serviceName: string; description: string; quantity: string; unit: string; cataloguePriceText?: string | null; priceConfirmed: boolean; agreedUnitPrice: string; taxTreatment: string; internalUnitCost: string; subtotal?: string; taxAmount?: string | null; total?: string; sortOrder: number };
type Job = { id: string; jobNumber: string; customerId: string; companyId: string | null; servicePriceItemId: string | null; serviceType: string | null; title: string; description: string | null; privateNotes: string | null; customerVisibleNotes: string | null; serviceDate: string | null; status: string; estimatedPrice: string | null; finalPrice: string | null; materialCost: string | null; otherCost: string | null; startTime: string | null; endTime: string | null; workDurationMinutes: number | null; files: Array<{ id: string }>; lineItems: LineItem[] };

const newLine = (): LineItem => ({ cataloguePriceItemId: '', serviceName: '', description: '', quantity: '1', unit: 'item', priceConfirmed: false, agreedUnitPrice: '', taxTreatment: 'UNCONFIRMED', internalUnitCost: '', sortOrder: 0 });
const blank = (customerId = ''): Job => ({ id: '', jobNumber: '', customerId, companyId: '', servicePriceItemId: '', serviceType: '', title: '', description: '', privateNotes: '', customerVisibleNotes: '', serviceDate: '', status: 'PLANNED', estimatedPrice: '', finalPrice: '', materialCost: '', otherCost: '', startTime: '', endTime: '', workDurationMinutes: null, files: [], lineItems: [] });
const localInput = (value: string | null) => value ? value.slice(0, 16) : '';
const localized = (value: unknown, fallback = '') => value && typeof value === 'object' ? ((value as Record<string, string>).de || (value as Record<string, string>).en || Object.values(value as Record<string, string>).find(Boolean) || fallback) : fallback;
const normalizeJob = (job: Job): Job => ({ ...job, lineItems: (job.lineItems ?? []).map((item) => ({ ...item, cataloguePriceItemId: item.cataloguePriceItemId ?? '', description: item.description ?? '', internalUnitCost: item.internalUnitCost ?? '' })) });
function priceDetails(price: string) {
  const lower = price.toLocaleLowerCase('de-DE');
  const mode = /(?:\/|pro\s+)(?:месяц|monat|month)|monthly/.test(lower) ? 'MONTHLY' : /(?:от|\bab\b|\bfrom\b)/.test(lower) ? 'FROM' : /(?:\/|pro\s+)(?:час|stunde|hour)/.test(lower) ? 'HOURLY' : lower.includes('%') ? 'PERCENTAGE' : /€/.test(price) ? 'FIXED' : 'MANUAL';
  const amount = price.match(/\d[\d\s]*(?:[.,]\d{1,2})?/)?.[0]?.replace(/\s/g, '').replace(',', '.') ?? '';
  return { mode, amount, unit: mode === 'MONTHLY' ? 'month' : mode === 'HOURLY' ? 'hour' : mode === 'PERCENTAGE' ? 'percent' : 'item' };
}

export function ServiceJobManager({ initialJobs, customers, priceItems, initialCustomerId, initialJobId }: { initialJobs: Job[]; customers: Customer[]; priceItems: PriceItem[]; initialCustomerId: string; initialJobId: string }) {
  const [jobs, setJobs] = useState(initialJobs); const first = initialJobId ? initialJobs.find((j) => j.id === initialJobId) : initialCustomerId ? undefined : initialJobs[0]; const [draft, setDraft] = useState<Job>(() => first ?? blank(initialCustomerId)); const [savedDraft, setSavedDraft] = useState<Job>(() => first ?? blank(initialCustomerId)); const [message, setMessage] = useState(''); const [fieldErrors, setFieldErrors] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const actionLock = useRef(false);
  const selectedCustomer = useMemo(() => customers.find((c) => c.id === draft.customerId), [customers, draft.customerId]);
  const customerName = (c: Customer) => [c.firstName, c.lastName].filter(Boolean).join(' ') || c.company?.name || c.customerNumber;
  const dirty = JSON.stringify(draft) !== JSON.stringify(savedDraft);
  function select(job?: Job) { const next = normalizeJob(job ?? blank(initialCustomerId)); setDraft(next); setSavedDraft(next); setMessage(''); setFieldErrors({}); }
  function update(key: keyof Job, value: unknown) { setDraft((d) => ({ ...d, [key]: value })); }
  function updateLine(index: number, patch: Partial<LineItem>) { setDraft((current) => ({ ...current, lineItems: current.lineItems.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) })); }
  function selectCatalogue(index: number, id: string) { const source = priceItems.find((item) => item.id === id); if (!source) { updateLine(index, { cataloguePriceItemId: '', priceConfirmed: false }); return; } const details = priceDetails(source.price); updateLine(index, { cataloguePriceItemId: source.id, serviceName: localized(source.name, source.code), description: localized(source.note), unit: details.unit, agreedUnitPrice: details.amount, cataloguePriceText: source.price, priceConfirmed: details.mode === 'FIXED' || details.mode === 'HOURLY' }); }
  function addLine(source: 'catalogue' | 'custom') { const index = draft.lineItems.length; update('lineItems', [...draft.lineItems, { ...newLine(), sortOrder: index }]); setMessage(source === 'catalogue' ? 'Choose a catalogue service in the new line.' : 'Complete the new custom service line.'); }
  function lineFromEstimate() { if (!draft.estimatedPrice || draft.lineItems.length) return; update('lineItems', [{ ...newLine(), serviceName: draft.title, description: draft.customerVisibleNotes || draft.description || '', agreedUnitPrice: draft.estimatedPrice, priceConfirmed: false }]); setMessage('Review the service description, price, and tax treatment, then save the job.'); }
  function validationErrors() { const errors: Record<string, string> = {}; if (!draft.customerId) errors.customerId = 'Select a customer.'; if (!draft.title.trim()) errors.title = 'Enter a job title.'; draft.lineItems.forEach((item, index) => { if (!item.serviceName.trim()) errors[`lineItems.${index}.serviceName`] = 'Enter a service name.'; if (!item.quantity) errors[`lineItems.${index}.quantity`] = 'Enter a quantity.'; if (!item.unit) errors[`lineItems.${index}.unit`] = 'Enter a unit.'; if (!item.agreedUnitPrice) errors[`lineItems.${index}.agreedUnitPrice`] = 'Enter the agreed price.'; }); return errors; }
  async function save(): Promise<Job | null> {
    const clientErrors = validationErrors(); setFieldErrors(clientErrors); if (Object.keys(clientErrors).length) { setMessage('Please correct the highlighted fields.'); return null; }
    setBusy(true); setMessage('Saving service job…');
    const body = { customerId: draft.customerId, companyId: selectedCustomer?.companyId ?? draft.companyId ?? '', servicePriceItemId: draft.servicePriceItemId ?? '', serviceType: draft.serviceType ?? '', title: draft.title, description: draft.description ?? '', privateNotes: draft.privateNotes ?? '', customerVisibleNotes: draft.customerVisibleNotes ?? '', serviceDate: draft.serviceDate ? new Date(draft.serviceDate).toISOString() : '', status: draft.status, estimatedPrice: draft.estimatedPrice ?? '', finalPrice: draft.finalPrice ?? '', materialCost: draft.materialCost ?? '', otherCost: draft.otherCost ?? '', startTime: draft.startTime ? new Date(draft.startTime).toISOString() : '', endTime: draft.endTime ? new Date(draft.endTime).toISOString() : '', workDurationMinutes: draft.workDurationMinutes === null ? null : Number(draft.workDurationMinutes), lineItems: draft.lineItems.map((item, index) => ({ cataloguePriceItemId: item.cataloguePriceItemId, serviceName: item.serviceName, description: item.description, quantity: item.quantity, unit: item.unit, agreedUnitPrice: item.agreedUnitPrice, priceConfirmed: item.priceConfirmed, taxTreatment: item.taxTreatment, internalUnitCost: item.internalUnitCost, sortOrder: index })) };
    try { const response = await fetch(draft.id ? `/api/admin/service-jobs/${draft.id}` : '/api/admin/service-jobs', { method: draft.id ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) { const serverFields = data.details?.fieldErrors as Record<string, string[]> | undefined; if (serverFields) setFieldErrors(Object.fromEntries(Object.entries(serverFields).map(([key, values]) => [key, values[0]]))); throw new Error(data.error === 'INVALID_SERVICE_JOB' ? 'Some job fields are invalid.' : data.error ?? `HTTP ${response.status}`); } const saved = normalizeJob(data as Job); setJobs((current) => current.some((j) => j.id === saved.id) ? current.map((j) => j.id === saved.id ? saved : j) : [saved, ...current]); setDraft(saved); setSavedDraft(saved); setFieldErrors({}); setMessage(`${saved.jobNumber} saved.`); return saved; }
    catch (error) { setMessage(`Could not save: ${error instanceof Error ? error.message : 'Unknown error'}`); return null; } finally { setBusy(false); }
  }
  async function createInvoice(saveFirst = false) { if (actionLock.current) return; actionLock.current = true; try { let source = draft; if (saveFirst || dirty) { const saved = await save(); if (!saved) return; source = saved; } if (!source.id || !source.lineItems.length) { setMessage('Add and save at least one service before creating an invoice.'); document.querySelector('.job-lines')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); return; } setBusy(true); setMessage('Creating invoice draft…'); const response = await fetch('/api/admin/invoices', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ serviceJobId: source.id }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error === 'INVOICE_JOB_HAS_NO_LINES' ? 'Add and save at least one service before creating an invoice.' : data.error ?? `HTTP ${response.status}`); window.location.assign(`/dashboard/invoices?invoiceId=${data.id}`); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not create invoice draft.'); } finally { setBusy(false); actionLock.current = false; } }
  const jobSubtotal = draft.lineItems.reduce((sum, item) => sum + (item.subtotal ? Number(item.subtotal) : (Number(item.agreedUnitPrice) || 0) * (Number(item.quantity) || 0)), 0);
  return <div className="workbench-layout"><aside className="panel workbench-list"><button className="admin-primary" onClick={() => select()}><Plus size={17} />New service job</button>{jobs.map((job) => <button className={draft.id === job.id ? 'is-active' : ''} key={job.id} onClick={() => select(job)}><strong>{job.title}</strong><span>{job.jobNumber} · {job.status.replace('_',' ')}</span></button>)}</aside>
    <section className="panel job-editor"><div className="project-editor__toolbar"><div><span className="eyebrow">{draft.jobNumber || 'New work order'}</span><h2>{draft.id ? 'Service job details' : 'Create service job'}</h2></div><div>{draft.id ? <button className="admin-secondary" onClick={() => createInvoice(dirty)} disabled={busy}><ReceiptText size={17} />{dirty ? 'Save and create draft' : 'Create invoice draft'}</button> : null}<button className="admin-primary" onClick={() => void save()} disabled={busy}><Save size={17} />Save job</button></div></div>{message ? <p className="admin-message" aria-live="polite">{message}</p> : null}
      <div className="admin-form-grid"><label className={fieldErrors.customerId ? 'field-error' : ''}>Customer<select value={draft.customerId} onChange={(e) => update('customerId', e.target.value)} aria-invalid={Boolean(fieldErrors.customerId)}><option value="">Select customer</option>{customers.map((c) => <option key={c.id} value={c.id}>{c.customerNumber} — {customerName(c)}{c.status === 'ARCHIVED' ? ' (archived)' : ''}</option>)}</select>{fieldErrors.customerId ? <span>{fieldErrors.customerId}</span> : null}</label><label>Status<select value={draft.status} onChange={(e) => update('status', e.target.value)}>{['PLANNED','IN_PROGRESS','WAITING_CUSTOMER','COMPLETED','CANCELLED'].map((v) => <option key={v}>{v.replace('_',' ')}</option>)}</select></label>
      <label className={`admin-span-2 ${fieldErrors.title ? 'field-error' : ''}`}>Title<input value={draft.title} onChange={(e) => update('title', e.target.value)} placeholder="Laptop cleaning and Windows optimization" aria-invalid={Boolean(fieldErrors.title)} />{fieldErrors.title ? <span>{fieldErrors.title}</span> : null}</label><label>Service type<input value={draft.serviceType ?? ''} onChange={(e) => update('serviceType', e.target.value)} /></label><label>Service date<input type="date" value={draft.serviceDate?.slice(0,10) ?? ''} onChange={(e) => update('serviceDate', e.target.value)} /></label>
      <label>Start time<input type="datetime-local" value={localInput(draft.startTime)} onChange={(e) => update('startTime', e.target.value)} /></label><label>End time<input type="datetime-local" value={localInput(draft.endTime)} onChange={(e) => update('endTime', e.target.value)} /></label><label>Work duration (minutes)<input type="number" min="0" value={draft.workDurationMinutes ?? ''} onChange={(e) => update('workDurationMinutes', e.target.value ? Number(e.target.value) : null)} /></label><label>Legacy estimated price (€)<input inputMode="decimal" value={draft.estimatedPrice ?? ''} onChange={(e) => update('estimatedPrice', e.target.value)} /></label>
      <label className="admin-span-2">Work performed / description<textarea rows={6} value={draft.description ?? ''} onChange={(e) => update('description', e.target.value)} /></label><label className="admin-span-2">Customer-facing work summary<textarea rows={4} value={draft.customerVisibleNotes ?? ''} onChange={(e) => update('customerVisibleNotes', e.target.value)} /></label><label className="admin-span-2">Private internal notes<textarea rows={5} value={draft.privateNotes ?? ''} onChange={(e) => update('privateNotes', e.target.value)} /></label></div>
      <section className="job-lines" id="services-and-prices"><div className="job-lines__heading"><div><h3>Services and prices</h3><p>Saved lines are snapshots. Editing them never changes the public catalogue.</p></div><div className="job-line-actions"><button className="admin-secondary" type="button" onClick={() => addLine('catalogue')}><ListPlus size={16} />Add from catalogue</button><button className="admin-secondary" type="button" onClick={() => addLine('custom')}><Plus size={16} />Add custom service</button></div></div>
        {!draft.lineItems.length && draft.estimatedPrice ? <div className="estimate-conversion"><p>This historical job has an estimate of <strong>{Number(draft.estimatedPrice).toLocaleString('de-DE', { style: 'currency', currency: 'EUR' })}</strong>, but no billable service lines.</p><button className="admin-secondary" type="button" onClick={lineFromEstimate}><ArrowDownToLine size={16} />Create service line from existing estimate</button></div> : null}
        {draft.lineItems.map((item, index) => <article className="job-line" key={item.id ?? index}><div className="job-line__toolbar"><strong>Line {index + 1}</strong><button className="icon-danger" type="button" aria-label={`Delete line ${index + 1}`} onClick={() => update('lineItems', draft.lineItems.filter((_, i) => i !== index))}><Trash2 size={16} /></button></div><div className="admin-form-grid">
          <label className="admin-span-2">Catalogue service (optional)<select value={item.cataloguePriceItemId} onChange={(e) => selectCatalogue(index, e.target.value)}><option value="">Custom private service</option>{priceItems.map((source) => <option key={source.id} value={source.id}>{source.code} — {localized(source.name, source.code)} — {source.price}</option>)}</select></label>
          <label className={fieldErrors[`lineItems.${index}.serviceName`] ? 'field-error' : ''}>Service name<input value={item.serviceName} onChange={(e) => updateLine(index, { serviceName: e.target.value })} />{fieldErrors[`lineItems.${index}.serviceName`] ? <span>{fieldErrors[`lineItems.${index}.serviceName`]}</span> : null}</label><label className={fieldErrors[`lineItems.${index}.unit`] ? 'field-error' : ''}>Unit<input value={item.unit} onChange={(e) => updateLine(index, { unit: e.target.value })} />{fieldErrors[`lineItems.${index}.unit`] ? <span>{fieldErrors[`lineItems.${index}.unit`]}</span> : null}</label>
          <label className={fieldErrors[`lineItems.${index}.quantity`] ? 'field-error' : ''}>Quantity<input inputMode="decimal" value={item.quantity} onChange={(e) => updateLine(index, { quantity: e.target.value })} />{fieldErrors[`lineItems.${index}.quantity`] ? <span>{fieldErrors[`lineItems.${index}.quantity`]}</span> : null}</label><label className={fieldErrors[`lineItems.${index}.agreedUnitPrice`] ? 'field-error' : ''}>Agreed unit price (€)<input inputMode="decimal" value={item.agreedUnitPrice} onChange={(e) => updateLine(index, { agreedUnitPrice: e.target.value, priceConfirmed: false })} />{fieldErrors[`lineItems.${index}.agreedUnitPrice`] ? <span>{fieldErrors[`lineItems.${index}.agreedUnitPrice`]}</span> : null}</label>
          <label>Tax treatment<select value={item.taxTreatment} onChange={(e) => updateLine(index, { taxTreatment: e.target.value })}><option value="UNCONFIRMED">Not confirmed</option><option value="VAT_STANDARD">German VAT 19%</option><option value="VAT_REDUCED">German VAT 7%</option><option value="ZERO_RATED">Zero-rated</option><option value="EXEMPT">Tax exempt</option><option value="KLEINUNTERNEHMER">Kleinunternehmer</option></select></label><label>Internal unit cost (€)<input inputMode="decimal" value={item.internalUnitCost ?? ''} onChange={(e) => updateLine(index, { internalUnitCost: e.target.value })} /></label>
          <label className="admin-span-2">Customer-facing description<textarea rows={3} value={item.description ?? ''} onChange={(e) => updateLine(index, { description: e.target.value })} /></label><p className="line-total admin-span-2">Line total: <strong>{((Number(item.quantity) || 0) * (Number(item.agreedUnitPrice) || 0)).toLocaleString('de-DE', { style: 'currency', currency: 'EUR' })}</strong></p>
          <label className="admin-checkbox admin-span-2"><input type="checkbox" checked={item.priceConfirmed} onChange={(e) => updateLine(index, { priceConfirmed: e.target.checked })} />I confirmed this job-specific price{item.cataloguePriceText ? ` (catalogue: ${item.cataloguePriceText})` : ''}. No recurring billing is created.</label>
        </div></article>)}
        {!draft.lineItems.length ? <div className="empty-line-items"><p>Add and save at least one service before creating an invoice.</p><button className="admin-secondary" type="button" onClick={() => addLine('custom')}>Add a service</button></div> : <p className="job-total">Job total before unconfirmed tax: <strong>{jobSubtotal.toLocaleString('de-DE', { style: 'currency', currency: 'EUR' })}</strong></p>}
      </section>
      <section className="private-files"><h3>Private work photos & documents</h3><p>{draft.files.length ? `${draft.files.length} private files attached.` : 'No files attached.'} Upload remains disabled until private object storage is connected.</p>{draft.customerId ? <Link href={`/dashboard/customers/${draft.customerId}`}>Open customer profile</Link> : null}</section>
    </section></div>;
}
