'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { Plus, Save, Trash2 } from 'lucide-react';

type Customer = { id: string; customerNumber: string; firstName: string | null; lastName: string | null; companyId: string | null; company: { name: string } | null };
type PriceItem = { id: string; code: string; name: unknown; note: unknown; price: string };
type LineItem = { id?: string; cataloguePriceItemId: string; serviceName: string; description: string; quantity: string; unit: string; cataloguePriceText?: string | null; priceConfirmed: boolean; agreedUnitPrice: string; taxTreatment: string; internalUnitCost: string; subtotal?: string; taxAmount?: string | null; total?: string; sortOrder: number };
type Job = { id: string; jobNumber: string; customerId: string; companyId: string | null; servicePriceItemId: string | null; serviceType: string | null; title: string; description: string | null; privateNotes: string | null; customerVisibleNotes: string | null; serviceDate: string | null; status: string; estimatedPrice: string | null; finalPrice: string | null; materialCost: string | null; otherCost: string | null; startTime: string | null; endTime: string | null; workDurationMinutes: number | null; files: Array<{ id: string }>; lineItems: LineItem[] };

const newLine = (): LineItem => ({ cataloguePriceItemId: '', serviceName: '', description: '', quantity: '1', unit: 'item', priceConfirmed: false, agreedUnitPrice: '', taxTreatment: 'UNCONFIRMED', internalUnitCost: '', sortOrder: 0 });
const blank = (customerId = ''): Job => ({ id: '', jobNumber: '', customerId, companyId: '', servicePriceItemId: '', serviceType: '', title: '', description: '', privateNotes: '', customerVisibleNotes: '', serviceDate: '', status: 'PLANNED', estimatedPrice: '', finalPrice: '', materialCost: '', otherCost: '', startTime: '', endTime: '', workDurationMinutes: null, files: [], lineItems: [] });
const localInput = (value: string | null) => value ? value.slice(0, 16) : '';
const localized = (value: unknown, fallback = '') => value && typeof value === 'object' ? ((value as Record<string, string>).de || (value as Record<string, string>).en || Object.values(value as Record<string, string>).find(Boolean) || fallback) : fallback;
const normalizeJob = (job: Job): Job => ({ ...job, lineItems: (job.lineItems ?? []).map((item) => ({ ...item, cataloguePriceItemId: item.cataloguePriceItemId ?? '', description: item.description ?? '', internalUnitCost: item.internalUnitCost ?? '' })) });
function priceDetails(price: string) {
  const lower = price.toLocaleLowerCase('de-DE');
  const mode = /(?:\/|pro\s+)(?:месяц|monat|month)|monthly/.test(lower) ? 'MONTHLY' : /(?:от|\bab\b|\bfrom\b)/.test(lower) ? 'FROM' : /(?:\/|pro\s+)(?:час|stunde|hour)/.test(lower) ? 'HOURLY' : lower.includes('%') ? 'PERCENTAGE' : /€/.test(price) ? 'FIXED' : 'MANUAL';
  const amount = price.match(/\d[\d\s]*(?:[.,]\d{1,2})?/)?.[0]?.replace(/\s/g, '').replace(',', '.') ?? '';
  return { mode, amount, unit: mode === 'MONTHLY' ? 'month' : mode === 'HOURLY' ? 'hour' : mode === 'PERCENTAGE' ? 'percent' : 'item' };
}

export function ServiceJobManager({ initialJobs, customers, priceItems, initialCustomerId, initialJobId }: { initialJobs: Job[]; customers: Customer[]; priceItems: PriceItem[]; initialCustomerId: string; initialJobId: string }) {
  const [jobs, setJobs] = useState(initialJobs); const first = initialJobId ? initialJobs.find((j) => j.id === initialJobId) : initialCustomerId ? undefined : initialJobs[0]; const [draft, setDraft] = useState<Job>(() => first ?? blank(initialCustomerId)); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const selectedCustomer = useMemo(() => customers.find((c) => c.id === draft.customerId), [customers, draft.customerId]);
  const customerName = (c: Customer) => [c.firstName, c.lastName].filter(Boolean).join(' ') || c.company?.name || c.customerNumber;
  function select(job?: Job) { setDraft(job ?? blank(initialCustomerId)); setMessage(''); }
  function update(key: keyof Job, value: unknown) { setDraft((d) => ({ ...d, [key]: value })); }
  function updateLine(index: number, patch: Partial<LineItem>) { setDraft((current) => ({ ...current, lineItems: current.lineItems.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) })); }
  function selectCatalogue(index: number, id: string) { const source = priceItems.find((item) => item.id === id); if (!source) { updateLine(index, { cataloguePriceItemId: '', priceConfirmed: false }); return; } const details = priceDetails(source.price); updateLine(index, { cataloguePriceItemId: source.id, serviceName: localized(source.name, source.code), description: localized(source.note), unit: details.unit, agreedUnitPrice: details.amount, cataloguePriceText: source.price, priceConfirmed: details.mode === 'FIXED' || details.mode === 'HOURLY' }); }
  async function save() {
    if (!draft.customerId || !draft.title.trim()) { setMessage('Customer and title are required.'); return; }
    if (draft.lineItems.some((item) => !item.serviceName.trim() || !item.agreedUnitPrice || !item.quantity || !item.unit)) { setMessage('Complete every service line item before saving.'); return; }
    setBusy(true); setMessage('Saving service job…');
    const body = { ...draft, companyId: selectedCustomer?.companyId ?? '', serviceDate: draft.serviceDate ? new Date(draft.serviceDate).toISOString() : '', startTime: draft.startTime ? new Date(draft.startTime).toISOString() : '', endTime: draft.endTime ? new Date(draft.endTime).toISOString() : '', workDurationMinutes: draft.workDurationMinutes === null ? null : Number(draft.workDurationMinutes), lineItems: draft.lineItems.map((item, index) => ({ id: item.id ?? '', cataloguePriceItemId: item.cataloguePriceItemId, serviceName: item.serviceName, description: item.description, quantity: item.quantity, unit: item.unit, agreedUnitPrice: item.agreedUnitPrice, priceConfirmed: item.priceConfirmed, taxTreatment: item.taxTreatment, internalUnitCost: item.internalUnitCost, sortOrder: index })) };
    try { const response = await fetch(draft.id ? `/api/admin/service-jobs/${draft.id}` : '/api/admin/service-jobs', { method: draft.id ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(Object.entries(body).filter(([key]) => !['id','jobNumber','files'].includes(key)))) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? `HTTP ${response.status}`); const saved = normalizeJob(data as Job); setJobs((current) => current.some((j) => j.id === saved.id) ? current.map((j) => j.id === saved.id ? saved : j) : [saved, ...current]); setDraft(saved); setMessage(`${saved.jobNumber} saved.`); }
    catch (error) { setMessage(`Could not save: ${error instanceof Error ? error.message : 'Unknown error'}`); } finally { setBusy(false); }
  }
  const jobSubtotal = draft.lineItems.reduce((sum, item) => sum + (item.subtotal ? Number(item.subtotal) : (Number(item.agreedUnitPrice) || 0) * (Number(item.quantity) || 0)), 0);
  return <div className="workbench-layout"><aside className="panel workbench-list"><button className="admin-primary" onClick={() => select()}><Plus size={17} />New service job</button>{jobs.map((job) => <button className={draft.id === job.id ? 'is-active' : ''} key={job.id} onClick={() => select(job)}><strong>{job.title}</strong><span>{job.jobNumber} · {job.status.replace('_',' ')}</span></button>)}</aside>
    <section className="panel"><div className="project-editor__toolbar"><div><span className="eyebrow">{draft.jobNumber || 'New work order'}</span><h2>{draft.id ? 'Service job details' : 'Create service job'}</h2></div><button className="admin-primary" onClick={save} disabled={busy}><Save size={17} />Save job</button></div>{message ? <p className="admin-message" aria-live="polite">{message}</p> : null}
      <div className="admin-form-grid"><label>Customer<select value={draft.customerId} onChange={(e) => update('customerId', e.target.value)}><option value="">Select customer</option>{customers.map((c) => <option key={c.id} value={c.id}>{c.customerNumber} — {customerName(c)}</option>)}</select></label><label>Status<select value={draft.status} onChange={(e) => update('status', e.target.value)}>{['PLANNED','IN_PROGRESS','WAITING_CUSTOMER','COMPLETED','CANCELLED'].map((v) => <option key={v}>{v.replace('_',' ')}</option>)}</select></label>
      <label className="admin-span-2">Title<input value={draft.title} onChange={(e) => update('title', e.target.value)} placeholder="Laptop cleaning and Windows optimization" /></label><label>Service type<input value={draft.serviceType ?? ''} onChange={(e) => update('serviceType', e.target.value)} /></label><label>Service date<input type="date" value={draft.serviceDate?.slice(0,10) ?? ''} onChange={(e) => update('serviceDate', e.target.value)} /></label>
      <label>Start time<input type="datetime-local" value={localInput(draft.startTime)} onChange={(e) => update('startTime', e.target.value)} /></label><label>End time<input type="datetime-local" value={localInput(draft.endTime)} onChange={(e) => update('endTime', e.target.value)} /></label><label>Work duration (minutes)<input type="number" min="0" value={draft.workDurationMinutes ?? ''} onChange={(e) => update('workDurationMinutes', e.target.value ? Number(e.target.value) : null)} /></label><label>Legacy estimated price (€)<input inputMode="decimal" value={draft.estimatedPrice ?? ''} onChange={(e) => update('estimatedPrice', e.target.value)} /></label>
      <label className="admin-span-2">Work performed / description<textarea rows={6} value={draft.description ?? ''} onChange={(e) => update('description', e.target.value)} /></label><label className="admin-span-2">Customer-facing work summary<textarea rows={4} value={draft.customerVisibleNotes ?? ''} onChange={(e) => update('customerVisibleNotes', e.target.value)} /></label><label className="admin-span-2">Private internal notes<textarea rows={5} value={draft.privateNotes ?? ''} onChange={(e) => update('privateNotes', e.target.value)} /></label></div>
      <section className="job-lines"><div className="job-lines__heading"><div><h3>Services and customer prices</h3><p>Saved lines are snapshots. Editing them never changes the public catalogue.</p></div><button className="admin-secondary" type="button" onClick={() => update('lineItems', [...draft.lineItems, { ...newLine(), sortOrder: draft.lineItems.length }])}><Plus size={16} />Add service</button></div>
        {draft.lineItems.map((item, index) => <article className="job-line" key={item.id ?? index}><div className="job-line__toolbar"><strong>Line {index + 1}</strong><button className="icon-danger" type="button" aria-label={`Delete line ${index + 1}`} onClick={() => update('lineItems', draft.lineItems.filter((_, i) => i !== index))}><Trash2 size={16} /></button></div><div className="admin-form-grid">
          <label className="admin-span-2">Catalogue service (optional)<select value={item.cataloguePriceItemId} onChange={(e) => selectCatalogue(index, e.target.value)}><option value="">Custom private service</option>{priceItems.map((source) => <option key={source.id} value={source.id}>{source.code} — {localized(source.name, source.code)} — {source.price}</option>)}</select></label>
          <label>Service name<input value={item.serviceName} onChange={(e) => updateLine(index, { serviceName: e.target.value })} /></label><label>Unit<input value={item.unit} onChange={(e) => updateLine(index, { unit: e.target.value })} /></label>
          <label>Quantity<input inputMode="decimal" value={item.quantity} onChange={(e) => updateLine(index, { quantity: e.target.value })} /></label><label>Agreed unit price (€)<input inputMode="decimal" value={item.agreedUnitPrice} onChange={(e) => updateLine(index, { agreedUnitPrice: e.target.value, priceConfirmed: false })} /></label>
          <label>Tax treatment<select value={item.taxTreatment} onChange={(e) => updateLine(index, { taxTreatment: e.target.value })}><option value="UNCONFIRMED">Not confirmed</option><option value="VAT_STANDARD">German VAT 19%</option><option value="VAT_REDUCED">German VAT 7%</option><option value="ZERO_RATED">Zero-rated</option><option value="EXEMPT">Tax exempt</option><option value="KLEINUNTERNEHMER">Kleinunternehmer</option></select></label><label>Internal unit cost (€)<input inputMode="decimal" value={item.internalUnitCost ?? ''} onChange={(e) => updateLine(index, { internalUnitCost: e.target.value })} /></label>
          <label className="admin-span-2">Customer-facing description<textarea rows={3} value={item.description ?? ''} onChange={(e) => updateLine(index, { description: e.target.value })} /></label>
          <label className="admin-checkbox admin-span-2"><input type="checkbox" checked={item.priceConfirmed} onChange={(e) => updateLine(index, { priceConfirmed: e.target.checked })} />I confirmed this job-specific price{item.cataloguePriceText ? ` (catalogue: ${item.cataloguePriceText})` : ''}. No recurring billing is created.</label>
        </div></article>)}
        {!draft.lineItems.length ? <p className="empty-line-items">No billable services yet. Existing legacy job prices remain preserved above.</p> : <p className="job-total">Current subtotal before unconfirmed tax: <strong>{jobSubtotal.toLocaleString('de-DE', { style: 'currency', currency: 'EUR' })}</strong></p>}
      </section>
      <section className="private-files"><h3>Private work photos & documents</h3><p>{draft.files.length ? `${draft.files.length} private files attached.` : 'No files attached.'} Upload remains disabled until private object storage is connected.</p>{draft.customerId ? <Link href={`/dashboard/customers/${draft.customerId}`}>Open customer profile</Link> : null}</section>
    </section></div>;
}
