'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { Plus, Save } from 'lucide-react';

type Customer = { id: string; customerNumber: string; firstName: string | null; lastName: string | null; companyId: string | null; company: { name: string } | null };
type PriceItem = { id: string; code: string; name: unknown };
type Job = { id: string; jobNumber: string; customerId: string; companyId: string | null; servicePriceItemId: string | null; serviceType: string | null; title: string; description: string | null; privateNotes: string | null; customerVisibleNotes: string | null; serviceDate: string | null; status: string; estimatedPrice: string | null; finalPrice: string | null; materialCost: string | null; otherCost: string | null; startTime: string | null; endTime: string | null; workDurationMinutes: number | null; files: Array<{ id: string }> };
const blank = (customerId = '') => ({ id: '', jobNumber: '', customerId, companyId: '', servicePriceItemId: '', serviceType: '', title: '', description: '', privateNotes: '', customerVisibleNotes: '', serviceDate: '', status: 'PLANNED', estimatedPrice: '', finalPrice: '', materialCost: '', otherCost: '', startTime: '', endTime: '', workDurationMinutes: null as number | null, files: [] as Array<{ id: string }> });
const localInput = (value: string | null) => value ? value.slice(0, 16) : '';

export function ServiceJobManager({ initialJobs, customers, priceItems, initialCustomerId, initialJobId }: { initialJobs: Job[]; customers: Customer[]; priceItems: PriceItem[]; initialCustomerId: string; initialJobId: string }) {
  const [jobs, setJobs] = useState(initialJobs); const first = initialJobs.find((j) => j.id === initialJobId) ?? initialJobs[0]; const [draft, setDraft] = useState<Job>(() => first ?? blank(initialCustomerId)); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  const selectedCustomer = useMemo(() => customers.find((c) => c.id === draft.customerId), [customers, draft.customerId]);
  const customerName = (c: Customer) => [c.firstName, c.lastName].filter(Boolean).join(' ') || c.company?.name || c.customerNumber;
  const priceName = (item: PriceItem) => { const value = item.name && typeof item.name === 'object' ? item.name as Record<string,string> : {}; return value.en || value.de || item.code; };
  function select(job?: Job) { setDraft(job ?? blank(initialCustomerId)); setMessage(''); }
  function update(key: keyof Job, value: unknown) { setDraft((d) => ({ ...d, [key]: value })); }
  async function save() {
    if (!draft.customerId || !draft.title.trim()) { setMessage('Customer and title are required.'); return; }
    setBusy(true); setMessage('Saving service job…');
    const body = { ...draft, companyId: selectedCustomer?.companyId ?? '', serviceDate: draft.serviceDate ? new Date(draft.serviceDate).toISOString() : '', startTime: draft.startTime ? new Date(draft.startTime).toISOString() : '', endTime: draft.endTime ? new Date(draft.endTime).toISOString() : '', workDurationMinutes: draft.workDurationMinutes === null ? null : Number(draft.workDurationMinutes) };
    try { const response = await fetch(draft.id ? `/api/admin/service-jobs/${draft.id}` : '/api/admin/service-jobs', { method: draft.id ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(Object.entries(body).filter(([key]) => !['id','jobNumber','files'].includes(key)))) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? `HTTP ${response.status}`); const saved: Job = { ...data, estimatedPrice: data.estimatedPrice?.toString() ?? null, finalPrice: data.finalPrice?.toString() ?? null, materialCost: data.materialCost?.toString() ?? null, otherCost: data.otherCost?.toString() ?? null, serviceDate: data.serviceDate, startTime: data.startTime, endTime: data.endTime }; setJobs((current) => current.some((j) => j.id === saved.id) ? current.map((j) => j.id === saved.id ? saved : j) : [saved, ...current]); setDraft(saved); setMessage(`${saved.jobNumber} saved.`); }
    catch (error) { setMessage(`Could not save: ${error instanceof Error ? error.message : 'Unknown error'}`); } finally { setBusy(false); }
  }
  return <div className="workbench-layout"><aside className="panel workbench-list"><button className="admin-primary" onClick={() => select()}><Plus size={17} />New service job</button>{jobs.map((job) => <button className={draft.id === job.id ? 'is-active' : ''} key={job.id} onClick={() => select(job)}><strong>{job.title}</strong><span>{job.jobNumber} · {job.status.replace('_',' ')}</span></button>)}</aside>
    <section className="panel"><div className="project-editor__toolbar"><div><span className="eyebrow">{draft.jobNumber || 'New work order'}</span><h2>{draft.id ? 'Service job details' : 'Create service job'}</h2></div><button className="admin-primary" onClick={save} disabled={busy}><Save size={17} />Save job</button></div>{message ? <p className="admin-message" aria-live="polite">{message}</p> : null}
      <div className="admin-form-grid"><label>Customer<select value={draft.customerId} onChange={(e) => update('customerId', e.target.value)}><option value="">Select customer</option>{customers.map((c) => <option key={c.id} value={c.id}>{c.customerNumber} — {customerName(c)}</option>)}</select></label><label>Status<select value={draft.status} onChange={(e) => update('status', e.target.value)}>{['PLANNED','IN_PROGRESS','WAITING_CUSTOMER','COMPLETED','CANCELLED'].map((v) => <option key={v}>{v.replace('_',' ')}</option>)}</select></label>
      <label className="admin-span-2">Title<input value={draft.title} onChange={(e) => update('title', e.target.value)} placeholder="Laptop cleaning and Windows optimization" /></label><label>Service type<input value={draft.serviceType ?? ''} onChange={(e) => update('serviceType', e.target.value)} /></label><label>Price catalogue item<select value={draft.servicePriceItemId ?? ''} onChange={(e) => update('servicePriceItemId', e.target.value)}><option value="">Not linked</option>{priceItems.map((p) => <option key={p.id} value={p.id}>{p.code} — {priceName(p)}</option>)}</select></label>
      <label>Service date<input type="date" value={draft.serviceDate?.slice(0,10) ?? ''} onChange={(e) => update('serviceDate', e.target.value)} /></label><label>Work duration (minutes)<input type="number" min="0" value={draft.workDurationMinutes ?? ''} onChange={(e) => update('workDurationMinutes', e.target.value ? Number(e.target.value) : null)} /></label>
      <label>Start time<input type="datetime-local" value={localInput(draft.startTime)} onChange={(e) => update('startTime', e.target.value)} /></label><label>End time<input type="datetime-local" value={localInput(draft.endTime)} onChange={(e) => update('endTime', e.target.value)} /></label>
      <label>Estimated price (€)<input inputMode="decimal" value={draft.estimatedPrice ?? ''} onChange={(e) => update('estimatedPrice', e.target.value)} /></label><label>Final price (€)<input inputMode="decimal" value={draft.finalPrice ?? ''} onChange={(e) => update('finalPrice', e.target.value)} /></label><label>Material cost (€)<input inputMode="decimal" value={draft.materialCost ?? ''} onChange={(e) => update('materialCost', e.target.value)} /></label><label>Other cost (€)<input inputMode="decimal" value={draft.otherCost ?? ''} onChange={(e) => update('otherCost', e.target.value)} /></label>
      <label className="admin-span-2">Work performed / description<textarea rows={6} value={draft.description ?? ''} onChange={(e) => update('description', e.target.value)} /></label><label className="admin-span-2">Customer-visible notes<textarea rows={4} value={draft.customerVisibleNotes ?? ''} onChange={(e) => update('customerVisibleNotes', e.target.value)} /></label><label className="admin-span-2">Private notes<textarea rows={5} value={draft.privateNotes ?? ''} onChange={(e) => update('privateNotes', e.target.value)} /></label></div>
      <section className="private-files"><h3>Private work photos & documents</h3><p>{draft.files.length ? `${draft.files.length} private files attached.` : 'No files attached.'} Upload activation is held until a private object-storage provider is connected; customer binaries are never placed in public APIs or the portfolio media table.</p>{draft.customerId ? <Link href={`/dashboard/customers/${draft.customerId}`}>Open customer profile</Link> : null}</section>
    </section></div>;
}
