'use client';

import { useState } from 'react';
import { Download, Plus, Save, Send, Trash2 } from 'lucide-react';

type Settings = { legalName: string; street: string; postalCode: string; city: string; country: string; email: string; phone: string; taxMode: string; taxNumber: string | null; vatId: string | null; taxStatement: string | null; bankAccountHolder: string | null; iban: string | null; bic: string | null; bankName: string | null; paymentTermsDays: number | null; paymentInstructions: string | null; settingsConfirmedAt: string | null };
type Line = { id?: string; serviceName: string; description: string | null; quantity: string; unit: string; unitPrice: string; taxTreatment: string; subtotal: string; taxAmount: string | null; total: string };
type Payment = { id: string; amount: string; paidAt: string; method: string | null; reference: string | null };
type Invoice = { id: string; invoiceNumber: string | null; status: string; customerId: string; serviceJobId: string | null; issueDate: string | null; dueDate: string | null; serviceDateFrom: string | null; serviceDateTo: string | null; recipientName: string; recipientCompany: string | null; recipientEmail: string | null; recipientStreet: string; recipientPostalCode: string; recipientCity: string; recipientCountry: string; customerReference: string | null; notes: string | null; subtotal: string; taxTotal: string | null; total: string; paidTotal: string; outstanding: string; lines: Line[]; payments: Payment[]; customer: { customerNumber: string }; serviceJob: { jobNumber: string; title: string } | null };

const dateInput = (value: string | null) => value?.slice(0, 10) ?? '';
const isoDate = (value: string) => value ? new Date(`${value}T12:00:00.000Z`).toISOString() : '';
const money = (value: string) => Number(value || 0).toLocaleString('de-DE', { style: 'currency', currency: 'EUR' });
const emptyLine = (): Line => ({ serviceName: '', description: '', quantity: '1', unit: 'item', unitPrice: '', taxTreatment: 'UNCONFIRMED', subtotal: '0', taxAmount: null, total: '0' });
const issueMessages: Record<string, string> = { BILLING_SETTINGS_UNCONFIRMED: 'Confirm the business billing and tax settings before issuing.', TAX_IDENTIFIER_REQUIRED: 'Enter a tax number or VAT ID before issuing.', INVOICE_DETAILS_INCOMPLETE: 'Complete the recipient address and issue date before issuing.', INVOICE_TAX_INCOMPLETE: 'Confirm the tax treatment for every invoice line before issuing.', INVOICE_TAX_MISMATCH: 'The invoice line tax treatment does not match the confirmed business tax treatment.', TAX_STATEMENT_REQUIRED: 'Enter the required legal tax wording before issuing.' };

export function InvoiceManager({ initialInvoices, initialSettings, initialInvoiceId }: { initialInvoices: Invoice[]; initialSettings: Settings; initialInvoiceId: string }) {
  const [invoices, setInvoices] = useState(initialInvoices); const [draft, setDraft] = useState<Invoice | null>(() => initialInvoices.find((row) => row.id === initialInvoiceId) ?? initialInvoices[0] ?? null);
  const [settings, setSettings] = useState(initialSettings); const [settingsOpen, setSettingsOpen] = useState(!initialSettings.settingsConfirmedAt); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [confirmSettings, setConfirmSettings] = useState(false);
  const [payment, setPayment] = useState({ amount: '', paidAt: new Date().toISOString().slice(0, 10), method: '', reference: '', note: '' });
  const setInvoice = (key: keyof Invoice, value: unknown) => setDraft((current) => current ? { ...current, [key]: value } : current);
  const setSetting = (key: keyof Settings, value: unknown) => setSettings((current) => ({ ...current, [key]: value }));
  const setLine = (index: number, patch: Partial<Line>) => setDraft((current) => current ? { ...current, lines: current.lines.map((line, i) => i === index ? { ...line, ...patch } : line) } : current);
  const replace = (saved: Invoice) => { setInvoices((current) => current.some((row) => row.id === saved.id) ? current.map((row) => row.id === saved.id ? saved : row) : [saved, ...current]); setDraft(saved); };
  async function saveSettings() { setBusy(true); setMessage('Saving billing settings…'); try { const response = await fetch('/api/admin/billing-settings', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...settings, confirmSettings }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSettings(data); setConfirmSettings(false); setMessage(data.settingsConfirmedAt ? 'Billing settings saved and confirmed.' : 'Billing settings saved. Issuing remains disabled until confirmed.'); } catch (error) { setMessage(`Could not save settings: ${error instanceof Error ? error.message : 'Unknown error'}`); } finally { setBusy(false); } }
  async function saveDraft() { if (!draft || draft.status !== 'DRAFT') return; setBusy(true); setMessage('Saving invoice draft…'); const body = { customerId: draft.customerId, serviceJobId: draft.serviceJobId ?? '', issueDate: isoDate(dateInput(draft.issueDate)), dueDate: isoDate(dateInput(draft.dueDate)), serviceDateFrom: isoDate(dateInput(draft.serviceDateFrom)), serviceDateTo: isoDate(dateInput(draft.serviceDateTo)), recipientName: draft.recipientName, recipientCompany: draft.recipientCompany ?? '', recipientEmail: draft.recipientEmail ?? '', recipientStreet: draft.recipientStreet, recipientPostalCode: draft.recipientPostalCode, recipientCity: draft.recipientCity, recipientCountry: draft.recipientCountry, customerReference: draft.customerReference ?? '', notes: draft.notes ?? '', lines: draft.lines.map((line) => ({ serviceName: line.serviceName, description: line.description ?? '', quantity: line.quantity, unit: line.unit, unitPrice: line.unitPrice, taxTreatment: line.taxTreatment })) }; try { const response = await fetch(`/api/admin/invoices/${draft.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); replace(data); setMessage('Draft saved.'); } catch (error) { setMessage(`Could not save draft: ${error instanceof Error ? error.message : 'Unknown error'}`); } finally { setBusy(false); } }
  async function issue() { if (!draft || !confirm('Issue this invoice permanently? Its number, data and PDF will be frozen.')) return; setBusy(true); setMessage('Issuing invoice…'); try { const response = await fetch(`/api/admin/invoices/${draft.id}/issue`, { method: 'POST' }); const data = await response.json(); if (!response.ok) { if (issueMessages[data.error]) setSettingsOpen(true); throw new Error(issueMessages[data.error] ?? data.error); } replace(data); setMessage(`${data.invoiceNumber} issued and frozen.`); } catch (error) { setMessage(`Could not issue: ${error instanceof Error ? error.message : 'Unknown error'}`); } finally { setBusy(false); } }
  async function addPayment(event: React.FormEvent) { event.preventDefault(); if (!draft) return; setBusy(true); try { const response = await fetch(`/api/admin/invoices/${draft.id}/payments`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...payment, paidAt: isoDate(payment.paidAt) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); replace(data); setPayment({ amount: '', paidAt: new Date().toISOString().slice(0, 10), method: '', reference: '', note: '' }); setMessage('Payment recorded.'); } catch (error) { setMessage(`Could not record payment: ${error instanceof Error ? error.message : 'Unknown error'}`); } finally { setBusy(false); } }
  const missingForIssue = !draft || draft.status !== 'DRAFT' ? [] : [!settings.settingsConfirmedAt ? 'Confirm business billing and tax settings.' : '', !settings.taxNumber && !settings.vatId ? 'Enter a tax number or VAT ID.' : '', !draft.recipientStreet || !draft.recipientPostalCode || !draft.recipientCity ? 'Complete the recipient billing address.' : '', draft.lines.some((line) => line.taxTreatment === 'UNCONFIRMED') ? 'Confirm tax treatment for every line.' : ''].filter(Boolean);
  return <><details className="panel billing-settings" open={settingsOpen} onToggle={(event) => setSettingsOpen(event.currentTarget.open)}><summary><strong>Business billing settings</strong><span>{settings.settingsConfirmedAt ? 'Confirmed' : 'Issuing blocked — confirmation required'}</span></summary><div className="admin-form-grid">
    <label className="admin-span-2">Legal name<input value={settings.legalName} onChange={(e) => setSetting('legalName', e.target.value)} /></label><label>Street<input value={settings.street} onChange={(e) => setSetting('street', e.target.value)} /></label><label>Postal code<input value={settings.postalCode} onChange={(e) => setSetting('postalCode', e.target.value)} /></label><label>City<input value={settings.city} onChange={(e) => setSetting('city', e.target.value)} /></label><label>Country<input value={settings.country} onChange={(e) => setSetting('country', e.target.value)} /></label><label>Email<input type="email" value={settings.email} onChange={(e) => setSetting('email', e.target.value)} /></label><label>Phone<input value={settings.phone} onChange={(e) => setSetting('phone', e.target.value)} /></label>
    <label>Tax treatment<select value={settings.taxMode} onChange={(e) => { setSetting('taxMode', e.target.value); setConfirmSettings(false); }}><option value="UNCONFIRMED">Not confirmed</option><option value="VAT">VAT registered</option><option value="KLEINUNTERNEHMER">Kleinunternehmer</option><option value="EXEMPT">Tax exempt</option></select></label><label>Tax number<input value={settings.taxNumber ?? ''} onChange={(e) => setSetting('taxNumber', e.target.value)} autoComplete="off" /></label><label>VAT ID (optional)<input value={settings.vatId ?? ''} onChange={(e) => setSetting('vatId', e.target.value)} autoComplete="off" /></label><label>Payment terms (days)<input type="number" min="0" max="365" value={settings.paymentTermsDays ?? ''} onChange={(e) => setSetting('paymentTermsDays', e.target.value ? Number(e.target.value) : null)} /></label><label className="admin-span-2">Required tax statement / legal wording<textarea rows={2} value={settings.taxStatement ?? ''} onChange={(e) => setSetting('taxStatement', e.target.value)} /></label>
    <label>Account holder<input value={settings.bankAccountHolder ?? ''} onChange={(e) => setSetting('bankAccountHolder', e.target.value)} /></label><label>Bank name<input value={settings.bankName ?? ''} onChange={(e) => setSetting('bankName', e.target.value)} /></label><label>IBAN<input value={settings.iban ?? ''} onChange={(e) => setSetting('iban', e.target.value)} autoComplete="off" /></label><label>BIC<input value={settings.bic ?? ''} onChange={(e) => setSetting('bic', e.target.value)} autoComplete="off" /></label><label className="admin-span-2">Payment instructions<textarea rows={2} value={settings.paymentInstructions ?? ''} onChange={(e) => setSetting('paymentInstructions', e.target.value)} /></label><label className="admin-checkbox admin-span-2"><input type="checkbox" checked={confirmSettings} onChange={(e) => setConfirmSettings(e.target.checked)} />I confirm that the tax treatment and identifiers are correct for issuing invoices.</label><button className="admin-primary" onClick={saveSettings} disabled={busy}><Save size={16} />Save billing settings</button>
  </div></details>{message ? <p className="admin-message" aria-live="polite">{message}</p> : null}{missingForIssue.length ? <section className="invoice-requirements"><strong>Draft preview is available. Before final issuance:</strong><ul>{missingForIssue.map((item) => <li key={item}>{item}</li>)}</ul></section> : null}
  <div className="workbench-layout invoice-workbench"><aside className="panel workbench-list">{invoices.length ? invoices.map((invoice) => <button className={draft?.id === invoice.id ? 'is-active' : ''} key={invoice.id} onClick={() => { setDraft(invoice); setMessage(''); }}><strong>{invoice.invoiceNumber ?? 'DRAFT'} · {invoice.recipientName}</strong><span>{invoice.customer.customerNumber} · {money(invoice.total)} · {invoice.status}</span></button>) : <p>No invoices yet. Create one from a saved service job.</p>}</aside>
  <section className="panel invoice-editor">{draft ? <><div className="project-editor__toolbar"><div><span className="eyebrow">{draft.invoiceNumber ?? 'DRAFT'}</span><h2>{draft.recipientName}</h2></div><div>{draft.status === 'DRAFT' ? <button className="admin-primary" onClick={saveDraft} disabled={busy}><Save size={16} />Save draft</button> : null}<a className="admin-secondary" href={`/api/admin/invoices/${draft.id}/pdf`}><Download size={16} />{draft.status === 'DRAFT' ? 'Draft PDF' : 'Invoice PDF'}</a>{draft.status === 'DRAFT' ? <button className="admin-secondary" onClick={issue} disabled={busy}><Send size={16} />Issue</button> : null}</div></div>
    <fieldset disabled={draft.status !== 'DRAFT'}><div className="admin-form-grid"><label>Issue date<input type="date" value={dateInput(draft.issueDate)} onChange={(e) => setInvoice('issueDate', e.target.value)} /></label><label>Due date<input type="date" value={dateInput(draft.dueDate)} onChange={(e) => setInvoice('dueDate', e.target.value)} /></label><label>Service from<input type="date" value={dateInput(draft.serviceDateFrom)} onChange={(e) => setInvoice('serviceDateFrom', e.target.value)} /></label><label>Service to<input type="date" value={dateInput(draft.serviceDateTo)} onChange={(e) => setInvoice('serviceDateTo', e.target.value)} /></label><label>Recipient<input value={draft.recipientName} onChange={(e) => setInvoice('recipientName', e.target.value)} /></label><label>Company<input value={draft.recipientCompany ?? ''} onChange={(e) => setInvoice('recipientCompany', e.target.value)} /></label><label>Email<input type="email" value={draft.recipientEmail ?? ''} onChange={(e) => setInvoice('recipientEmail', e.target.value)} /></label><label>Street<input value={draft.recipientStreet} onChange={(e) => setInvoice('recipientStreet', e.target.value)} /></label><label>Postal code<input value={draft.recipientPostalCode} onChange={(e) => setInvoice('recipientPostalCode', e.target.value)} /></label><label>City<input value={draft.recipientCity} onChange={(e) => setInvoice('recipientCity', e.target.value)} /></label><label>Country<input value={draft.recipientCountry} onChange={(e) => setInvoice('recipientCountry', e.target.value)} /></label><label>Reference<input value={draft.customerReference ?? ''} onChange={(e) => setInvoice('customerReference', e.target.value)} /></label><label className="admin-span-2">Customer-visible invoice note<textarea rows={2} value={draft.notes ?? ''} onChange={(e) => setInvoice('notes', e.target.value)} /></label></div>
    <div className="invoice-lines"><div className="job-lines__heading"><h3>Invoice lines</h3>{draft.status === 'DRAFT' ? <button className="admin-secondary" type="button" onClick={() => setInvoice('lines', [...draft.lines, emptyLine()])}><Plus size={16} />Add line</button> : null}</div>{draft.lines.map((line, index) => <article className="job-line" key={line.id ?? index}><div className="job-line__toolbar"><strong>Line {index + 1}</strong>{draft.status === 'DRAFT' ? <button className="icon-danger" type="button" aria-label="Remove line" onClick={() => setInvoice('lines', draft.lines.filter((_, i) => i !== index))}><Trash2 size={15} /></button> : null}</div><div className="admin-form-grid"><label>Service<input value={line.serviceName} onChange={(e) => setLine(index, { serviceName: e.target.value })} /></label><label>Unit<input value={line.unit} onChange={(e) => setLine(index, { unit: e.target.value })} /></label><label>Quantity<input inputMode="decimal" value={line.quantity} onChange={(e) => setLine(index, { quantity: e.target.value })} /></label><label>Unit price (€)<input inputMode="decimal" value={line.unitPrice} onChange={(e) => setLine(index, { unitPrice: e.target.value })} /></label><label>Tax<select value={line.taxTreatment} onChange={(e) => setLine(index, { taxTreatment: e.target.value })}><option value="UNCONFIRMED">Not confirmed</option><option value="VAT_STANDARD">VAT 19%</option><option value="VAT_REDUCED">VAT 7%</option><option value="ZERO_RATED">Zero-rated</option><option value="EXEMPT">Exempt</option><option value="KLEINUNTERNEHMER">Kleinunternehmer</option></select></label><label className="admin-span-2">Description<textarea rows={2} value={line.description ?? ''} onChange={(e) => setLine(index, { description: e.target.value })} /></label></div></article>)}</div></fieldset>
    <div className="invoice-summary"><span>Subtotal <b>{money(draft.subtotal)}</b></span><span>Tax <b>{draft.taxTotal === null ? 'Not confirmed' : money(draft.taxTotal)}</b></span><span>Total <b>{money(draft.total)}</b></span><span>Paid <b>{money(draft.paidTotal)}</b></span><span>Outstanding <b>{money(draft.outstanding)}</b></span></div>
    {draft.status === 'ISSUED' ? <section className="payment-panel"><h3>Payments</h3><div className="compact-list">{draft.payments.map((entry) => <article key={entry.id}><strong>{money(entry.amount)}</strong><span>{new Date(entry.paidAt).toLocaleDateString('de-DE')} · {entry.method || 'Payment'}</span></article>)}</div>{Number(draft.outstanding) > 0 ? <form className="admin-form-grid" onSubmit={addPayment}><label>Amount (€)<input required inputMode="decimal" value={payment.amount} onChange={(e) => setPayment({ ...payment, amount: e.target.value })} /></label><label>Paid date<input required type="date" value={payment.paidAt} onChange={(e) => setPayment({ ...payment, paidAt: e.target.value })} /></label><label>Method<input value={payment.method} onChange={(e) => setPayment({ ...payment, method: e.target.value })} /></label><label>Reference<input value={payment.reference} onChange={(e) => setPayment({ ...payment, reference: e.target.value })} /></label><label className="admin-span-2">Note<input value={payment.note} onChange={(e) => setPayment({ ...payment, note: e.target.value })} /></label><button className="admin-primary" disabled={busy}>Record payment</button></form> : <p className="paid-banner">Paid in full</p>}</section> : null}
  </> : <div className="empty-state"><h2>No invoice selected</h2><p>Create an invoice draft from a saved service job.</p></div>}</section></div></>;
}
